import { useEffect, useState } from "react";
import { applyAdminEcologicalStatus, getAdminEcologicalStatus, prepareAdminEcologicalStatus, reviewAdminEcologicalStatus } from "../../services/api";

const statuses = ["PRESENT", "NATIVE", "NON_NATIVE", "INVASIVE", "ESTABLISHED", "TRANSIENT", "ERADICATED", "UNCERTAIN"];
const label = (value) => String(value || "Unknown").replaceAll("_", " ").toLowerCase().replace(/\b\w/g, (letter) => letter.toUpperCase());

export default function EcologicalStatusPanel({ jurisdictionId, taxonId, scientificName }) {
  const [current, setCurrent] = useState(null), [preparation, setPreparation] = useState(null), [selected, setSelected] = useState(["PRESENT"]), [source, setSource] = useState({ organization: "", title: "", reference: "", authority: "REVIEW_REQUIRED", evidenceType: "OTHER_REVIEWED_SOURCE" }), [error, setError] = useState(null), [busy, setBusy] = useState(false);
  useEffect(() => { if (jurisdictionId && taxonId) getAdminEcologicalStatus(jurisdictionId, taxonId).then(setCurrent).catch((reason) => setError(reason.message)); }, [jurisdictionId, taxonId]);
  const payload = (dryRun) => ({ jurisdiction_id: Number(jurisdictionId), source_organization: source.organization, source_title: source.title, source_reference: source.reference, evidence_type: source.evidenceType, authority_classification: source.authority, geographic_scope: { type: "JURISDICTION", jurisdiction_id: Number(jurisdictionId) }, limitations: [], assertions: [{ scientific_name: scientificName, statuses: selected }], dry_run: dryRun });
  async function run(action) { setBusy(true); setError(null); try { setPreparation(await action()); } catch (reason) { setError(reason.message); } finally { setBusy(false); } }
  async function review(disposition) { const reference = window.prompt("Scientific review reference:"); if (reference) await run(() => reviewAdminEcologicalStatus(preparation.id, preparation.candidates.map((item) => item.id), reference, disposition)); }
  return <section className="mt-5 rounded-xl border border-app-border bg-white p-5"><h2 className="font-bold">Jurisdiction ecological status</h2><p className="mt-1 text-xs text-app-muted">Explicit reviewed assertions only. Occurrence evidence and regional taxonomy do not establish ecological or invasive status.</p>
    <div className="mt-4 rounded-lg bg-slate-50 p-3 text-sm"><strong>Current reviewed projection</strong><p>{current?.projection?.projection_state ? label(current.projection.projection_state) : "Not evaluated"}</p><div className="mt-1 flex flex-wrap gap-1">{current?.projection?.statuses?.length ? current.projection.statuses.map((item) => <span key={item} className="rounded-full border border-teal-200 bg-teal-50 px-2 py-1 text-xs font-bold text-teal-900">{label(item)}</span>) : <span className="text-xs text-app-muted">No governed current status</span>}</div>{current?.projection?.conflicts?.length > 0 && <p className="mt-2 text-xs font-bold text-red-700">Conflicting approved assertions require review.</p>}</div>
    <div className="mt-4 grid gap-3 sm:grid-cols-2"><input value={source.organization} onChange={(event) => setSource({ ...source, organization: event.target.value })} placeholder="Source organization" className="rounded-lg border border-app-border px-3 py-2 text-sm" /><input value={source.title} onChange={(event) => setSource({ ...source, title: event.target.value })} placeholder="Source title" className="rounded-lg border border-app-border px-3 py-2 text-sm" /><input value={source.reference} onChange={(event) => setSource({ ...source, reference: event.target.value })} placeholder="Source URL or reference" className="rounded-lg border border-app-border px-3 py-2 text-sm" /><select value={source.authority} onChange={(event) => setSource({ ...source, authority: event.target.value })} className="rounded-lg border border-app-border px-3 py-2 text-sm"><option>REVIEW_REQUIRED</option><option>AUTHORITATIVE_FOR_JURISDICTION</option><option>SUPPORTING</option><option>CONFLICTING</option><option>INSUFFICIENT</option></select></div>
    <div className="mt-3 flex flex-wrap gap-2">{statuses.map((item) => <label key={item} className="flex items-center gap-1 rounded-full border border-app-border px-2 py-1 text-xs"><input type="checkbox" checked={selected.includes(item)} onChange={() => setSelected((values) => values.includes(item) ? values.filter((value) => value !== item) : [...values, item])} />{label(item)}</label>)}</div>
    <div className="mt-4 flex flex-wrap gap-2"><button disabled={busy || !scientificName} onClick={() => run(() => prepareAdminEcologicalStatus(payload(true)))} className="rounded-lg border border-app-border px-3 py-2 text-sm font-bold disabled:opacity-40">List preflight</button><button disabled={busy || !source.organization || !source.title || !source.reference} onClick={() => run(() => prepareAdminEcologicalStatus(payload(false)))} className="rounded-lg bg-teal-700 px-3 py-2 text-sm font-bold text-white disabled:opacity-40">Prepare assertion</button>{preparation?.id && <><button disabled={busy || source.authority !== "AUTHORITATIVE_FOR_JURISDICTION"} onClick={() => review("APPROVED")} className="rounded-lg bg-teal-700 px-3 py-2 text-sm font-bold text-white disabled:opacity-40">Approve</button><button disabled={busy} onClick={() => review("UNRESOLVED")} className="rounded-lg border border-amber-300 px-3 py-2 text-sm font-bold">Unresolved</button><button disabled={busy || preparation.workflow_status !== "APPROVED"} onClick={() => run(() => applyAdminEcologicalStatus(preparation.id))} className="rounded-lg bg-slate-900 px-3 py-2 text-sm font-bold text-white disabled:opacity-40">Apply reviewed status</button></>}</div>
    {preparation?.rows && <p className="mt-3 rounded-lg bg-slate-50 p-3 text-xs">Preflight: {Object.entries(preparation.counts || {}).map(([key, value]) => `${label(key)} ${value}`).join(" · ")}</p>}{preparation?.candidates?.map((item) => <div key={item.id} className="mt-2 rounded-lg border border-app-border p-3 text-xs"><strong>{item.scientific_name} · {item.statuses.map(label).join(" + ")}</strong><p>{label(item.preflight_classification)} · {label(item.review_status)}</p></div>)}
    {error && <p className="mt-3 rounded-lg bg-red-50 p-3 text-sm text-red-700">{error}</p>}<p className="mt-4 rounded-lg bg-amber-50 p-3 text-xs text-amber-900">Non-native, invasive, established, and occurrence are distinct scientific concepts. No numeric confidence is assigned.</p></section>;
}
