import { useEffect, useMemo, useState } from "react";
import { applyAdminOccurrenceEvidence, approveAdminOccurrenceCandidates, disposeAdminOccurrenceCandidates, getAdminOccurrencePreparation, getAdminOccurrenceSources, initializeAdminOccurrenceReview, prepareAdminOccurrenceEvidence } from "../../services/api";

const readable = (value) => String(value || "Unknown").replaceAll("_", " ").toLowerCase().replace(/\b\w/g, (letter) => letter.toUpperCase());
const labels = ["New in-boundary candidates", "Known legacy overlaps", "Outside jurisdiction", "Taxonomic / provenance review", "Applied evidence"];
function category(item) {
  if (item.applied_evidence_id) return "Applied evidence";
  if (item.boundary_reconciliation === "OUTSIDE_BOUNDARY") return "Outside jurisdiction";
  if (item.overlap_classification === "VERIFIED_OVERLAP") return "Known legacy overlaps";
  if (item.eligibility?.eligible) return "New in-boundary candidates";
  return "Taxonomic / provenance review";
}

export default function OccurrenceEvidencePanel({ jurisdictionId, taxonId }) {
  const [sources, setSources] = useState([]), [sourceKey, setSourceKey] = useState(""), [preparation, setPreparation] = useState(null), [selected, setSelected] = useState(new Set()), [busy, setBusy] = useState(false), [error, setError] = useState(null);
  useEffect(() => { getAdminOccurrenceSources().then((data) => { const available = data.sources || []; setSources(available); setSourceKey(available.find((source) => source.workflow_status === "ACTIVE")?.source_registration_id || ""); }).catch((reason) => setError(reason.message)); }, []);
  const candidates = useMemo(() => preparation?.candidates || [], [preparation]);
  const categorized = useMemo(() => labels.map((label) => [label, candidates.filter((candidate) => category(candidate) === label)]), [candidates]);
  const approvalSafe = selected.size > 0 && candidates.filter((candidate) => selected.has(candidate.id)).every((candidate) => candidate.eligibility?.eligible && !candidate.applied_evidence_id);
  async function execute(action, initialize = false) { setBusy(true); setError(null); try { let result = await action(); if (initialize && result.id) { await initializeAdminOccurrenceReview(result.id); result = await getAdminOccurrencePreparation(result.id); } setPreparation(result); setSelected(new Set()); } catch (reason) { setError(reason.message); } finally { setBusy(false); } }
  function toggle(candidate) { if (candidate.applied_evidence_id) return; setSelected((values) => { const next = new Set(values); next.has(candidate.id) ? next.delete(candidate.id) : next.add(candidate.id); return next; }); }
  async function approve() { const reference = window.prompt("Approval reference:"); if (reference) await execute(() => approveAdminOccurrenceCandidates(preparation.id, [...selected], reference)); }
  async function mark(disposition) { const reference = window.prompt("Review reference:"); if (reference) await execute(() => disposeAdminOccurrenceCandidates(preparation.id, [...selected], disposition, reference)); }
  const activeSource = sources.find((source) => source.source_registration_id === sourceKey);
  return <section className="mt-5 rounded-xl border border-app-border bg-white p-5">
    <h2 className="font-bold">Jurisdiction occurrence evidence</h2><p className="mt-1 text-xs text-app-muted">Governed event review only. Occurrence evidence does not assign ecological or invasive status.</p>
    {activeSource ? <><label className="mt-4 block text-xs font-bold">Active governed source<select value={sourceKey} onChange={(event) => setSourceKey(event.target.value)} className="mt-1 block w-full rounded-lg border border-app-border px-3 py-2 font-normal">{sources.filter((source) => source.workflow_status === "ACTIVE").map((source) => <option key={source.id} value={source.source_registration_id}>{source.source_name} · {source.scientific_provider} via {source.transport_interface}</option>)}</select></label><div className="mt-2 rounded-lg bg-slate-50 p-3 text-xs"><strong>{activeSource.workflow_status}</strong> · {activeSource.license} · {activeSource.configuration_version}<p className="text-app-muted">{activeSource.documentation_reference}</p></div></> : <p className="mt-4 rounded-lg bg-slate-50 p-4 text-sm">No ACTIVE governed source is available.</p>}
    <div className="mt-3 flex flex-wrap gap-2"><button disabled={busy || !jurisdictionId || !taxonId || !sourceKey} onClick={() => execute(() => prepareAdminOccurrenceEvidence(jurisdictionId, taxonId, sourceKey, true))} className="rounded-lg border border-app-border px-3 py-2 text-sm font-bold disabled:opacity-40">Preflight</button><button disabled={busy || !jurisdictionId || !taxonId || !sourceKey} onClick={() => execute(() => prepareAdminOccurrenceEvidence(jurisdictionId, taxonId, sourceKey), true)} className="rounded-lg bg-teal-700 px-3 py-2 text-sm font-bold text-white disabled:opacity-40">Prepare and classify</button>{preparation?.id && <><button disabled={!approvalSafe || busy} onClick={approve} className="rounded-lg bg-teal-700 px-3 py-2 text-sm font-bold text-white disabled:opacity-40">Approve eligible</button><button disabled={!selected.size || busy} onClick={() => mark("REVIEW_REQUIRED")} className="rounded-lg border border-amber-300 px-3 py-2 text-sm font-bold disabled:opacity-40">Needs review</button><button disabled={!selected.size || busy} onClick={() => mark("UNRESOLVED")} className="rounded-lg border border-app-border px-3 py-2 text-sm font-bold disabled:opacity-40">Unresolved</button><button disabled={busy || preparation.workflow_status !== "APPROVED"} onClick={() => execute(() => applyAdminOccurrenceEvidence(preparation.id))} className="rounded-lg bg-slate-900 px-3 py-2 text-sm font-bold text-white disabled:opacity-40">Apply approved new evidence</button></>}</div>
    {error && <p className="mt-3 rounded-lg bg-red-50 p-3 text-sm text-red-700">{error}</p>}
    {preparation?.summary && <div className="mt-4 grid gap-2 sm:grid-cols-4"><div className="rounded-lg bg-slate-50 p-3"><p className="text-[10px] font-bold uppercase text-app-muted">Candidates</p><strong>{preparation.summary.total}</strong></div>{categorized.slice(0,3).map(([label, items]) => <div key={label} className="rounded-lg bg-slate-50 p-3"><p className="text-[10px] font-bold uppercase text-app-muted">{label}</p><strong>{items.length}</strong></div>)}</div>}
    {categorized.map(([label, items]) => items.length > 0 && <div key={label} className="mt-5"><h3 className="mb-2 text-xs font-bold uppercase tracking-wide text-app-muted">{label} · {items.length}</h3><div className="max-h-[340px] overflow-auto rounded-lg border border-app-border"><table className="w-full text-left text-xs"><thead className="sticky top-0 bg-white"><tr><th className="p-2"></th><th className="p-2">Record</th><th className="p-2">Provider / license</th><th className="p-2">Reconciliation</th><th className="p-2">Disposition</th></tr></thead><tbody>{items.map((candidate) => <tr key={candidate.id} className="border-t border-app-border"><td className="p-2"><input aria-label={`Select candidate ${candidate.id}`} type="checkbox" disabled={Boolean(candidate.applied_evidence_id)} checked={selected.has(candidate.id)} onChange={() => toggle(candidate)} /></td><td className="p-2"><strong>{candidate.upstream_occurrence_id || candidate.provider_occurrence_id || "No stable ID"}</strong><p>{candidate.event_date ? String(candidate.event_date).slice(0,10) : "Date unavailable"} · {candidate.latitude}, {candidate.longitude}</p></td><td className="p-2"><strong>{candidate.source_metadata?.scientific_provider || "Provider unresolved"}</strong><p>{candidate.source_metadata?.transport_interface || "No transport"} · {candidate.source_metadata?.license || "License unresolved"}</p></td><td className="p-2">{readable(candidate.taxonomy_reconciliation)}<p>{readable(candidate.boundary_reconciliation)} · {readable(candidate.overlap_classification)}</p></td><td className="p-2"><strong>{readable(candidate.review_disposition)}</strong>{candidate.eligibility?.blocking_reasons?.map((reason) => <p key={reason} className="text-amber-700">{readable(reason)}</p>)}</td></tr>)}</tbody></table></div></div>)}
    <p className="mt-4 rounded-lg bg-amber-50 p-3 text-xs text-amber-900">Outside-boundary and known-overlap records remain in the controlled audit history but cannot be selected as new jurisdiction evidence.</p>
  </section>;
}
