import { useMemo, useState } from "react";
import { applyRegionalTaxonManifestItems, approveRegionalTaxonManifestItems, getRegionalTaxonManifest, parseScientificCorpusManifest, preflightRegionalTaxonManifest, prepareRegionalTaxonManifest, rejectRegionalTaxonManifestItem, retryRegionalTaxonManifestItems } from "../../services/api";

const label = (value) => String(value || "Unavailable").replaceAll("_", " ").toLowerCase().replace(/\b\w/g, (character) => character.toUpperCase());
const selectable = (item) => ["READY_FOR_REVIEW", "APPROVED", "FAILED"].includes(item.workflow_state);

export default function RegionalTaxonManifestPanel({ regions }) {
  const initialRegion = regions[0]?.id || "";
  const [regionId, setRegionId] = useState(initialRegion), [manifestId, setManifestId] = useState("caribbean-review-batch-1"), [operatorReference, setOperatorReference] = useState("");
  const [candidateText, setCandidateText] = useState(""), [inputFormat, setInputFormat] = useState("PASTED_NAMES"), [parsedCandidates, setParsedCandidates] = useState(null), [result, setResult] = useState(null), [selected, setSelected] = useState(new Set()), [busy, setBusy] = useState(false), [error, setError] = useState(null);
  const pastedCandidates = useMemo(() => candidateText.split(/\r?\n/).map((line) => line.trim()).filter(Boolean).map((submitted_scientific_name) => ({ submitted_scientific_name, candidate_source: "ADMIN_MANIFEST", source_reference: operatorReference || null })), [candidateText, operatorReference]);
  const candidates = parsedCandidates || (inputFormat === "PASTED_NAMES" ? pastedCandidates : []);
  const effectiveRegionId = regionId || regions[0]?.id || "";
  const payload = () => ({ manifest_id: manifestId, manifest_version: "1.0", region_id: Number(effectiveRegionId), operator_reference: operatorReference, provenance: { submitted_via: "ADMIN_TAXONOMY_CONSOLE" }, limitations: ["Regional review input only; not jurisdiction occurrence or ecological status."], candidates });
  const items = result?.items || result?.results || [];

  async function execute(action) { setBusy(true); setError(null); try { const response = await action(); setResult(response); setSelected(new Set()); return response; } catch (requestError) { setError(requestError.message); } finally { setBusy(false); } }
  async function refresh(runId = result?.id || result?.run_id) { if (runId) await execute(() => getRegionalTaxonManifest(runId)); }
  async function approve() { const reference = window.prompt("Approval reference:"); if (!reference) return; const response = await execute(() => approveRegionalTaxonManifestItems(result.id, [...selected], reference)); if (response) await refresh(response.run_id); }
  async function reject() { const reference = window.prompt("Rejection reference:"); if (!reference) return; const runId = result.id; await execute(() => Promise.all([...selected].map((itemId) => rejectRegionalTaxonManifestItem(runId, itemId, reference)))); await refresh(runId); }
  async function apply(retry = false) { if (!window.confirm(`${retry ? "Retry" : "Apply"} selected governed taxonomy items? This creates no jurisdiction science.`)) return; const response = await execute(() => retry ? retryRegionalTaxonManifestItems(result.id, [...selected]) : applyRegionalTaxonManifestItems(result.id, [...selected])); if (response) await refresh(response.run_id); }
  async function parseInput() { const response = await execute(() => parseScientificCorpusManifest(candidateText, inputFormat)); if (response) { setParsedCandidates(response.candidates.map((candidate) => ({ ...candidate, source_reference: candidate.source_reference || operatorReference || null }))); setResult(response); } }

  return <section className="mt-5 rounded-xl border border-app-border bg-white p-5">
    <div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="font-bold">Regional Catalog / Batch Onboarding</h2><p className="mt-1 max-w-3xl text-xs text-app-muted">Submit a reviewed candidate manifest for authoritative preflight. A regional catalog entry is not evidence that a species occurs in any jurisdiction.</p></div>{result?.execution_state && <span className="rounded-full bg-teal-50 px-3 py-1 text-xs font-bold text-teal-800">{label(result.execution_state)}</span>}</div>
    <div className="mt-4 grid gap-3 md:grid-cols-3"><label className="text-xs font-bold">Target region<select value={effectiveRegionId} onChange={(event) => setRegionId(event.target.value)} className="mt-1 block w-full rounded-lg border border-app-border px-3 py-2 text-sm font-normal">{regions.map((region) => <option key={region.id} value={region.id}>{region.name}</option>)}</select></label><label className="text-xs font-bold">Manifest ID<input value={manifestId} onChange={(event) => setManifestId(event.target.value)} className="mt-1 block w-full rounded-lg border border-app-border px-3 py-2 text-sm font-normal" /></label><label className="text-xs font-bold">Operator/source reference<input value={operatorReference} onChange={(event) => setOperatorReference(event.target.value)} className="mt-1 block w-full rounded-lg border border-app-border px-3 py-2 text-sm font-normal" placeholder="Required review-pool reference" /></label></div>
    <div className="mt-3 flex flex-wrap items-end gap-3"><label className="text-xs font-bold">Input format<select value={inputFormat} onChange={(event) => { setInputFormat(event.target.value); setParsedCandidates(null); }} className="mt-1 block rounded-lg border border-app-border px-3 py-2 text-sm font-normal"><option value="PASTED_NAMES">Pasted names</option><option value="CSV">CSV</option><option value="JSON">JSON</option></select></label><button disabled={busy || !candidateText.trim()} onClick={parseInput} className="rounded-lg border border-app-border px-3 py-2 text-sm font-bold disabled:opacity-40">Validate input</button><span className="pb-2 text-xs text-app-muted">Up to 10,000 candidates; validation performs no scientific writes.</span></div>
    <textarea rows="8" value={candidateText} onChange={(event) => { setCandidateText(event.target.value); setParsedCandidates(null); }} className="mt-3 w-full rounded-lg border border-app-border p-3 font-mono text-xs" placeholder={inputFormat === "CSV" ? "scientific_name,aphia_id,source_reference" : inputFormat === "JSON" ? '[{"scientific_name":"Pterois volitans"}]' : 'One scientific name per line\nPterois volitans'} />
    <div className="mt-3 flex flex-wrap gap-2"><button disabled={busy || !candidates.length || !operatorReference} onClick={() => execute(() => preflightRegionalTaxonManifest(payload()))} className="rounded-lg border border-app-border px-3 py-2 text-sm font-bold disabled:opacity-40">Run preflight</button><button disabled={busy || !candidates.length || !operatorReference} onClick={() => execute(() => prepareRegionalTaxonManifest(payload()))} className="rounded-lg bg-teal-700 px-3 py-2 text-sm font-bold text-white disabled:opacity-40">Prepare manifest</button>{result?.id && <><button disabled={busy || !selected.size} onClick={approve} className="rounded-lg bg-teal-700 px-3 py-2 text-sm font-bold text-white disabled:opacity-40">Approve selected</button><button disabled={busy || !selected.size} onClick={reject} className="rounded-lg border border-red-200 px-3 py-2 text-sm font-bold text-red-700 disabled:opacity-40">Reject selected</button><button disabled={busy || !selected.size} onClick={() => apply(false)} className="rounded-lg bg-slate-900 px-3 py-2 text-sm font-bold text-white disabled:opacity-40">Apply selected</button><button disabled={busy || !selected.size} onClick={() => apply(true)} className="rounded-lg border border-app-border px-3 py-2 text-sm font-bold disabled:opacity-40">Retry selected</button></>}</div>
    {error && <p className="mt-3 rounded-lg bg-red-50 p-3 text-sm text-red-700">{error}</p>}
    {result?.summary && <div className="mt-4 grid gap-2 sm:grid-cols-4">{[["Total", result.summary.total], ["Resolvable", result.summary.cleanly_resolvable], ["Already governed", result.summary.already_governed], ["Review / blocked", result.summary.requires_review_or_blocked]].map(([name, value]) => <div key={name} className="rounded-lg bg-slate-50 p-3"><p className="text-[10px] font-bold uppercase text-app-muted">{name}</p><strong className="text-lg">{value ?? 0}</strong></div>)}</div>}
    {items.length > 0 && <div className="mt-4 overflow-x-auto"><table className="w-full text-left text-xs"><thead><tr className="border-b border-app-border text-app-muted"><th className="p-2"></th><th className="p-2">Submitted identity</th><th className="p-2">Authoritative resolution</th><th className="p-2">Proposed action</th><th className="p-2">State / limitation</th></tr></thead><tbody>{items.map((item, index) => { const id = item.id; const submitted = item.submitted_identity || item.candidate || {}; const resolution = item.resolution || {}; return <tr key={id || index} className="border-b border-app-border align-top"><td className="p-2"><input type="checkbox" disabled={!id || !selectable(item)} checked={selected.has(id)} onChange={() => setSelected((values) => { const next = new Set(values); next.has(id) ? next.delete(id) : next.add(id); return next; })} /></td><td className="p-2"><strong>{submitted.submitted_scientific_name}</strong><p className="text-app-muted">{submitted.source_reference || "No candidate source reference"}</p></td><td className="p-2"><strong>{resolution.canonical_scientific_name || "Unresolved"}</strong><p>{resolution.rank} · {resolution.accepted_name_status}</p><p className="text-app-muted">{resolution.provider} {resolution.authoritative_identifier_scheme} {resolution.authoritative_identifier}</p><p className="text-app-muted">{resolution.authorship}</p></td><td className="p-2 font-bold">{label(item.proposed_action || item.status)}</td><td className="p-2"><strong>{label(item.workflow_state || item.status)}</strong><p className="text-red-700">{item.last_error || item.reason}</p></td></tr>; })}</tbody></table></div>}
    {result?.scientific_firewall && <div className={`mt-4 rounded-lg border p-3 text-xs ${result.scientific_firewall.status === "PASS" ? "border-teal-200 bg-teal-50 text-teal-900" : "border-red-200 bg-red-50 text-red-800"}`}><strong>Scientific firewall: {result.scientific_firewall.status}</strong><p className="mt-1">{result.scientific_firewall.statement}</p></div>}
    <p className="mt-4 rounded-lg bg-amber-50 p-3 text-xs font-medium text-amber-900">REGIONAL TAXON GOVERNANCE ≠ JURISDICTION SCIENTIFIC CONFIGURATION. Approval creates no occurrence, ecological status, model, training, or anomaly state.</p>
  </section>;
}
