"""Read-only contracts for future jurisdiction species pages."""
from ecological_status_governance import CONFLICT_PAIRS,EcologicalStatusGovernanceService
from sqlalchemy import func
from models import EcologicalStatusAssertion,GovernedOccurrenceEvidence,GovernedPublicMedia,JurisdictionBoundary,Observation,Species,SuitabilityDeployment,SpeciesProgram

class EcologicalStatusReadService:
 def __init__(self,session):self.session=session
 def species(self,jurisdiction_id,taxon_id):
  taxon=self.session.get(Species,taxon_id);projection=EcologicalStatusGovernanceService(self.session).projection(jurisdiction_id,taxon_id);assertions=self.session.query(EcologicalStatusAssertion).filter(EcologicalStatusAssertion.id.in_(projection["assertion_ids"])).all() if projection["assertion_ids"] else []
  sources=[{"organization":row.source_organization,"title":row.source_title,"reference":row.source_reference,"effective_from":row.effective_from} for row in assertions]
  evidence=self.session.query(GovernedOccurrenceEvidence).filter_by(jurisdiction_id=jurisdiction_id,taxon_id=taxon_id).order_by(GovernedOccurrenceEvidence.event_date).all()
  dated=[row.event_date for row in evidence if row.event_date]
  observations=self.session.query(Observation).filter(Observation.jurisdiction_id==jurisdiction_id,Observation.is_possible_duplicate.is_(False),Observation.verification_status.in_(["CONFIRMED","CORRECTED"]),func.lower(func.coalesce(Observation.verified_species,Observation.species))==func.lower(taxon.scientific_name)).order_by(Observation.id.desc()).all() if taxon else []
  deployment=self.session.query(SuitabilityDeployment).join(SpeciesProgram).filter(SpeciesProgram.jurisdiction_id==jurisdiction_id,SpeciesProgram.species_id==taxon_id,SuitabilityDeployment.status=="ACTIVE").first()
  return {"jurisdiction_id":jurisdiction_id,"taxon_id":taxon_id,"scientific_name":taxon.scientific_name if taxon else None,"common_name":taxon.common_name if taxon else None,"authorship":getattr(taxon,"scientific_name_authorship",None) if taxon else None,"authoritative_taxonomy":{"scheme":taxon.authoritative_identifier_scheme,"identifier":taxon.authoritative_identifier,"rank":taxon.taxonomic_rank} if taxon else None,"current_reviewed_status":projection if projection["projection_state"]=="CURRENT_APPROVED" else {**projection,"statuses":[]},"source_attribution":sources,"occurrence_summary":{"count":len(evidence),"dated_count":len(dated),"earliest":min(dated) if dated else None,"latest":max(dated) if dated else None},"occurrence_points":[{"latitude":row.latitude,"longitude":row.longitude,"event_date":row.event_date,"basis_of_record":row.basis_of_record} for row in evidence if row.latitude is not None and row.longitude is not None],"verified_observations":[{"id":row.id,"latitude":row.latitude,"longitude":row.longitude,"species":row.verified_species or row.species,"verification_status":row.verification_status} for row in observations],"suitability":{"available":deployment is not None,"model_version":deployment.model_version if deployment else None,"label":"Environmental habitat suitability; not confirmed presence." if deployment else None},"thumbnail_url":None,"detail_identifier":f"{jurisdiction_id}:{taxon_id}","semantics":"Current approved jurisdiction assertions and applied governed occurrence evidence only."}
 def marine_species(self,jurisdiction_id):
  rows=self.session.query(EcologicalStatusAssertion,Species).join(Species,Species.id==EcologicalStatusAssertion.taxon_id).filter(EcologicalStatusAssertion.jurisdiction_id==jurisdiction_id,EcologicalStatusAssertion.review_status=="APPROVED",EcologicalStatusAssertion.authority_classification=="AUTHORITATIVE_FOR_JURISDICTION",EcologicalStatusAssertion.lifecycle_state=="CURRENT").order_by(Species.scientific_name,EcologicalStatusAssertion.id).all();grouped={}
  for assertion,taxon in rows:grouped.setdefault(taxon.id,{"taxon":taxon,"assertions":[]})["assertions"].append(assertion)
  media_rows=self.session.query(GovernedPublicMedia).filter(GovernedPublicMedia.taxon_id.in_(grouped.keys()),GovernedPublicMedia.lifecycle_state=="PUBLIC",GovernedPublicMedia.public_visibility=="PUBLIC_APPROVED",GovernedPublicMedia.is_primary.is_(True)).all() if grouped else [];media_by_taxon={row.taxon_id:row for row in media_rows};result=[]
  for taxon_id,value in grouped.items():
   assertions=value["assertions"];statuses=sorted({row.asserted_status for row in assertions});conflicts=[sorted(pair) for pair in CONFLICT_PAIRS if pair.issubset(statuses)]
   if conflicts:continue
   taxon=value["taxon"];media=media_by_taxon.get(taxon_id);primary={"url":media.remote_url,"alt_text":f"{taxon.scientific_name} reference image","attribution_text":media.attribution_text,"license":media.license,"source_reference":media.source_reference} if media and media.remote_url and media.remote_url.startswith(("https://","http://")) else None;result.append({"jurisdiction_id":jurisdiction_id,"taxon_id":taxon_id,"scientific_name":taxon.scientific_name,"common_name":taxon.common_name,"current_reviewed_status":{"projection_state":"CURRENT_APPROVED","statuses":statuses,"assertion_ids":[row.id for row in assertions],"conflicts":[]},"source_attribution":[{"organization":row.source_organization,"title":row.source_title,"reference":row.source_reference,"effective_from":row.effective_from} for row in assertions],"primary_image":primary,"thumbnail_url":primary["url"] if primary else None,"detail_identifier":f"{jurisdiction_id}:{taxon_id}"})
  return result
 def invasive_species(self,jurisdiction_id):return [row for row in self.marine_species(jurisdiction_id) if "INVASIVE" in row["current_reviewed_status"]["statuses"]]
