"""Additive/idempotent Phase 12C-1 occurrence-evidence schema migration."""
import argparse
import sqlite3

PREPARATIONS = """CREATE TABLE IF NOT EXISTS occurrence_acquisition_preparations(
id INTEGER PRIMARY KEY,region_id INTEGER NOT NULL REFERENCES regions(id),jurisdiction_id INTEGER NOT NULL REFERENCES jurisdictions(id),taxon_id INTEGER NOT NULL REFERENCES species(id),source_key VARCHAR(128) NOT NULL,scientific_provider VARCHAR(256) NOT NULL,transport_interface VARCHAR(128),provider_dataset_id VARCHAR(256) NOT NULL,provider_dataset_version VARCHAR(128),source_reference VARCHAR(512) NOT NULL,license_json TEXT NOT NULL,acquisition_parameters_json TEXT NOT NULL,declared_extent_json TEXT NOT NULL,ownership_scope_json TEXT NOT NULL,limitations_json TEXT NOT NULL,raw_artifact_reference VARCHAR(512) NOT NULL,raw_artifact_sha256 VARCHAR(64) NOT NULL,normalized_content_fingerprint VARCHAR(64) NOT NULL,boundary_id INTEGER NOT NULL REFERENCES jurisdiction_boundaries(id),boundary_geometry_hash VARCHAR(64) NOT NULL,boundary_source_artifact_sha256 VARCHAR(64),dependency_fingerprint VARCHAR(64) NOT NULL UNIQUE,workflow_status VARCHAR(24) NOT NULL DEFAULT 'READY_FOR_REVIEW',prepared_by_user_id INTEGER NOT NULL REFERENCES users(id),prepared_at DATETIME NOT NULL,approved_by_user_id INTEGER REFERENCES users(id),approval_reference VARCHAR(256),approved_dependency_fingerprint VARCHAR(64),approved_at DATETIME,applied_at DATETIME,scientific_dataset_id INTEGER REFERENCES scientific_datasets(id),last_error TEXT,provenance_json TEXT NOT NULL,firewall_report_json TEXT)"""
CANDIDATES = """CREATE TABLE IF NOT EXISTS occurrence_candidate_records(
id INTEGER PRIMARY KEY,preparation_id INTEGER NOT NULL REFERENCES occurrence_acquisition_preparations(id) ON DELETE CASCADE,provider_occurrence_id VARCHAR(512),upstream_occurrence_id VARCHAR(512),event_id VARCHAR(512),catalog_specimen_id VARCHAR(512),observation_reference VARCHAR(512),original_scientific_name VARCHAR(512),reconciled_taxon_id INTEGER REFERENCES species(id),taxonomy_reconciliation VARCHAR(40) NOT NULL,latitude FLOAT,longitude FLOAT,event_date DATETIME,basis_of_record VARCHAR(128),occurrence_status VARCHAR(128),coordinate_uncertainty_m FLOAT,depth_m FLOAT,locality VARCHAR(512),boundary_reconciliation VARCHAR(32) NOT NULL,boundary_id INTEGER NOT NULL REFERENCES jurisdiction_boundaries(id),overlap_classification VARCHAR(32) NOT NULL,overlap_reason VARCHAR(256) NOT NULL,matching_evidence_ids_json TEXT NOT NULL,source_metadata_json TEXT NOT NULL,original_record_reference VARCHAR(512),normalization_version VARCHAR(64) NOT NULL,provenance_fingerprint VARCHAR(64) NOT NULL,review_status VARCHAR(24) NOT NULL DEFAULT 'PENDING_REVIEW',reviewed_by_user_id INTEGER REFERENCES users(id),review_reference VARCHAR(256),reviewed_at DATETIME,applied_evidence_id INTEGER REFERENCES governed_occurrence_evidence(id),UNIQUE(preparation_id,provenance_fingerprint))"""
EVIDENCE = """CREATE TABLE IF NOT EXISTS governed_occurrence_evidence(
id INTEGER PRIMARY KEY,preparation_id INTEGER NOT NULL REFERENCES occurrence_acquisition_preparations(id),candidate_record_id INTEGER NOT NULL UNIQUE REFERENCES occurrence_candidate_records(id),scientific_dataset_id INTEGER NOT NULL REFERENCES scientific_datasets(id),jurisdiction_id INTEGER NOT NULL REFERENCES jurisdictions(id),taxon_id INTEGER NOT NULL REFERENCES species(id),provider_occurrence_id VARCHAR(512),upstream_occurrence_id VARCHAR(512),event_id VARCHAR(512),catalog_specimen_id VARCHAR(512),latitude FLOAT,longitude FLOAT,event_date DATETIME,basis_of_record VARCHAR(128),boundary_id INTEGER NOT NULL REFERENCES jurisdiction_boundaries(id),evidence_fingerprint VARCHAR(64) NOT NULL UNIQUE,provenance_json TEXT NOT NULL,created_at DATETIME NOT NULL)"""

def run_migration(connection):
    before = {row[0] for row in connection.execute("SELECT name FROM sqlite_master WHERE type='table'")}
    with connection:
        for statement in (PREPARATIONS, CANDIDATES, EVIDENCE): connection.execute(statement)
        for table, column in (("occurrence_acquisition_preparations","jurisdiction_id"),("occurrence_acquisition_preparations","taxon_id"),("occurrence_acquisition_preparations","workflow_status"),("occurrence_candidate_records","preparation_id"),("occurrence_candidate_records","taxonomy_reconciliation"),("occurrence_candidate_records","boundary_reconciliation"),("occurrence_candidate_records","overlap_classification"),("governed_occurrence_evidence","jurisdiction_id"),("governed_occurrence_evidence","taxon_id")):
            connection.execute(f"CREATE INDEX IF NOT EXISTS ix_{table}_{column} ON {table}({column})")
    names=("occurrence_acquisition_preparations","occurrence_candidate_records","governed_occurrence_evidence")
    return {name: name not in before for name in names}

if __name__ == "__main__":
    parser=argparse.ArgumentParser();parser.add_argument("--database",default="marine_observations.db");args=parser.parse_args();connection=sqlite3.connect(args.database);print(run_migration(connection));connection.close()
