import sqlite3
conn = sqlite3.connect('marine_observations.db')
cur = conn.cursor()
print('Observations:', cur.execute('SELECT COUNT(*) FROM observations').fetchone()[0])
print('Verified CONFIRMED:', cur.execute("SELECT COUNT(*) FROM observations WHERE verification_status='CONFIRMED'").fetchone()[0])
print('Verified CORRECTED:', cur.execute("SELECT COUNT(*) FROM observations WHERE verification_status='CORRECTED'").fetchone()[0])
print('Unresolved identification:', cur.execute("SELECT COUNT(*) FROM observations WHERE identification_status='unresolved'").fetchone()[0])
print('Historical occurrences:', cur.execute('SELECT COUNT(*) FROM historical_occurrences').fetchone()[0])
print('Historical occurrence species:', cur.execute('SELECT COUNT(DISTINCT scientific_name) FROM historical_occurrences').fetchone()[0])
print('Species:', cur.execute('SELECT COUNT(*) FROM species').fetchone()[0])
print('SpeciesJurisdictionStatus:', cur.execute('SELECT COUNT(*) FROM species_jurisdiction_status').fetchone()[0])
print('SuitabilityDeployments:', cur.execute('SELECT COUNT(*) FROM suitability_deployments').fetchone()[0])
print('Suitability cells (scored):', cur.execute("SELECT COUNT(*) FROM habitat_suitability_v3_grid_cells WHERE prediction_status='SCORED'").fetchone()[0])
print('Distinct suitability cell coordinates:', cur.execute('SELECT COUNT(DISTINCT grid_cell_id) FROM habitat_suitability_v3_grid_cells').fetchone()[0])
print('Monitoring Priority generations:', cur.execute('SELECT COUNT(*) FROM next_area_snapshot_generations').fetchone()[0])
print('Active Monitoring Priority generations:', cur.execute("SELECT COUNT(*) FROM next_area_snapshot_generations WHERE is_active=1 AND status='ACTIVE'").fetchone()[0])
print('Monitoring Priority cells:', cur.execute('SELECT COUNT(*) FROM next_area_snapshot_cells').fetchone()[0])
print('Monitoring Priority cells (distinct grid_cell_id):', cur.execute('SELECT COUNT(DISTINCT grid_cell_id) FROM next_area_snapshot_cells').fetchone()[0])
print('Hotspots:', cur.execute('SELECT COUNT(*) FROM hotspot_service_species_activity').fetchone()[0])
conn.close()
