import { useCallback, useEffect, useState } from "react";
import { useAuth } from "../auth/AuthContext";
import {
  assignAdminObservation, claimAdminObservation, closeAdminObservation,
  getAdminObservationOperations, getAdminObservationQueue, getEligibleObservationReviewers,
  getPrivateObservationImage, requestAdminObservationInformation, rotateReporterLink,
  triageAdminObservation, updateAdminObservationDisposition, updateAdminObservationPriority,
} from "../services/api";

const label=(v)=>String(v||"").replaceAll("_"," ").toLowerCase().replace(/\b\w/g,c=>c.toUpperCase());
const age=(date)=>{const h=Math.max(0,Math.floor((Date.now()-new Date(date).getTime())/36e5));return h<24?`${h}h`:`${Math.floor(h/24)}d ${h%24}h`;};
const absolute=(path)=>`${window.location.origin}${path}`;

function PrivateImage({id,className}){
  const [src,setSrc]=useState(null);
  useEffect(()=>{let url,active=true;getPrivateObservationImage(id).then(value=>{url=value;if(active)setSrc(value)}).catch(()=>{});return()=>{active=false;if(url)URL.revokeObjectURL(url);};},[id]);
  return src?<img src={src} alt="Private submission evidence" className={className}/>:<div role="status" aria-label="Private image unavailable" className={`${className} grid place-items-center bg-slate-100 text-xs text-app-muted`}>Image unavailable</div>;
}

export default function AdminObservationOperationsPage(){
  const {user}=useAuth();
  const [items,setItems]=useState([]),[selected,setSelected]=useState(null),[detail,setDetail]=useState(null);
  const [reviewers,setReviewers]=useState([]),[assignee,setAssignee]=useState("");
  const [view,setView]=useState("ALL"),[priority,setPriority]=useState(""),[state,setState]=useState("");
  const [delivery,setDelivery]=useState(null),[error,setError]=useState(null);
  const load=useCallback(()=>getAdminObservationQueue({assigned_reviewer_id:view==="MY"?user.id:undefined,priority,workflow_state:state}).then(data=>{let rows=data.items||[];if(view==="UNASSIGNED")rows=rows.filter(item=>!item.assigned_reviewer_user_id);setItems(rows);setSelected(current=>rows.find(item=>item.observation_id===current?.observation_id)||rows[0]||null);}).catch(e=>setError(e.message)),[priority,state,user.id,view]);
  useEffect(()=>{load();},[load]);
  useEffect(()=>{if(!selected)return;Promise.all([getAdminObservationOperations(selected.observation_id),getEligibleObservationReviewers(selected.jurisdiction_id)]).then(([caseDetail,eligible])=>{setDetail(caseDetail);setReviewers(eligible.items||[]);setAssignee(String(caseDetail.case.assigned_reviewer_user_id||""));}).catch(e=>setError(e.message));},[selected]);
  async function act(fn){try{setError(null);const result=await fn();await load();if(selected)setDetail(await getAdminObservationOperations(selected.observation_id));return result;}catch(e){setError(e.message);return null;}}
  async function requestInformation(){const message=window.prompt("What additional information is required?");if(!message)return;const result=await act(()=>requestAdminObservationInformation(selected.observation_id,message));if(result?.reporter_response_url)setDelivery({url:absolute(result.reporter_response_url),message:"Additional information was requested for this marine sighting. Use this private link to respond."});}
  async function prepareLink(){const result=await act(()=>rotateReporterLink(selected.observation_id));if(result)setDelivery({url:absolute(result.reporter_response_url),message:result.message});}
  async function copy(value){try{await navigator.clipboard.writeText(value);}catch{setError("Copy was blocked by the browser. Select the text and copy it manually.");}}
  async function closeOrReopen(){const reopening=selected.workflow_state==="CLOSED";const reason=window.prompt(reopening?"Reason for reopening:":"Closure reason:");if(!reason)return;if(!window.confirm(reopening?"Reopen this operational case?":"Close this case? A final disposition is required."))return;await act(()=>closeAdminObservation(selected.observation_id,reopening,reason));}
  return <main className="grid min-h-[calc(100vh-64px)] grid-cols-1 bg-slate-50 lg:grid-cols-[360px_1fr]">
    <aside className="border-r border-app-border bg-white"><header className="sticky top-0 z-10 space-y-3 border-b bg-white p-4"><h1 className="font-bold">Observation review</h1><p className="text-xs text-app-muted">{items.length} authorized cases · priority is not ecological severity</p><div className="flex gap-1">{[["ALL","All authorized"],["MY","My cases"],["UNASSIGNED","Unassigned"]].map(([key,text])=><button key={key} onClick={()=>setView(key)} className={`rounded px-2 py-1 text-xs ${view===key?"bg-teal-700 text-white":"bg-slate-100"}`}>{text}</button>)}</div><div className="grid grid-cols-2 gap-2"><select aria-label="Priority filter" value={priority} onChange={e=>setPriority(e.target.value)} className="rounded border p-1.5 text-xs"><option value="">All priorities</option>{["LOW","NORMAL","HIGH","URGENT"].map(v=><option key={v}>{v}</option>)}</select><select aria-label="State filter" value={state} onChange={e=>setState(e.target.value)} className="rounded border p-1.5 text-xs"><option value="">All states</option>{["TRIAGE_REQUIRED","IN_REVIEW","AWAITING_IDENTIFICATION","AWAITING_EXPERT_REVIEW","AWAITING_REPORTER_INFORMATION","VERIFIED","CORRECTED","CLOSED"].map(v=><option key={v}>{v}</option>)}</select></div></header><div className="max-h-[calc(100vh-220px)] overflow-auto">{items.length?items.map(item=><button key={item.observation_id} onClick={()=>{setSelected(item);setDelivery(null);}} className={`grid w-full grid-cols-[56px_1fr] gap-3 border-b p-3 text-left ${selected?.observation_id===item.observation_id?"border-l-2 border-l-teal-700 bg-teal-50":"bg-white"}`}><PrivateImage id={item.observation_id} className="h-14 w-14 rounded object-cover"/><span><strong className="block truncate text-sm">{item.resolved_identity.species||"Unresolved observation"}</strong><small>#{item.observation_id} · {age(item.submitted_at)} old</small><small className="block text-app-muted">{label(item.workflow_state)} · {label(item.operational_priority)}</small></span></button>):<p className="p-8 text-center text-sm text-app-muted">No cases match these filters.</p>}</div></aside>
    <section className="p-5">{selected?<div className="mx-auto max-w-6xl space-y-4"><header className="flex flex-wrap justify-between gap-2"><div><h2 className="text-2xl font-bold">{selected.resolved_identity.species||"Identification unresolved"}</h2><p className="text-xs text-app-muted">Jurisdiction #{selected.jurisdiction_id} · case age {age(selected.submitted_at)}</p></div><div className="flex flex-wrap gap-2"><button onClick={()=>act(()=>claimAdminObservation(selected.observation_id))} className="rounded border border-teal-700 px-3 py-2 text-sm text-teal-800">Assign to me</button><button onClick={()=>act(()=>triageAdminObservation(selected.observation_id))} className="rounded bg-teal-700 px-4 py-2 text-sm font-bold text-white">Run triage</button><button onClick={closeOrReopen} className="rounded border px-3 py-2 text-sm">{selected.workflow_state==="CLOSED"?"Reopen case":"Close case"}</button></div></header>
      <div className="grid gap-4 xl:grid-cols-2"><article className="rounded-xl border bg-white p-5"><h3 className="font-bold">Report and identification</h3><PrivateImage id={selected.observation_id} className="mt-3 max-h-80 w-full rounded bg-slate-950 object-contain"/><p className="mt-3 text-sm">Reporter suggestion: {selected.reporter_suggestion||"Not specified"}</p><p className="text-sm">AI assistance: {selected.ai_identification.species||"Unresolved"}</p><p className="text-sm">Expert decision: {selected.expert_identification.species||"Not reviewed"}</p></article><article className="rounded-xl border bg-white p-5"><h3 className="font-bold">Assignment and review actions</h3><div className="mt-3 flex gap-2"><select aria-label="Assigned reviewer" value={assignee} onChange={e=>setAssignee(e.target.value)} className="min-w-0 flex-1 rounded border p-2 text-sm"><option value="">Unassigned</option>{reviewers.map(r=><option key={r.user_id} value={r.user_id}>{r.display_name}</option>)}</select><button onClick={()=>act(()=>assignAdminObservation(selected.observation_id,assignee?Number(assignee):null,selected.assigned_reviewer_user_id))} className="rounded bg-teal-700 px-3 py-2 text-sm font-bold text-white">Apply</button></div><div className="mt-3 flex gap-2">{["NORMAL","HIGH","URGENT"].map(value=><button key={value} onClick={()=>act(()=>updateAdminObservationPriority(selected.observation_id,value,"Manual queue adjustment"))} className="rounded border px-2 py-1 text-xs">{value}</button>)}</div><div className="mt-3 flex flex-wrap gap-2">{["CONFIRMED","CORRECTED","UNRESOLVED","REJECTED","CONFIRMED_DUPLICATE","NOT_DUPLICATE"].map(value=><button key={value} onClick={()=>{const species=value==="CORRECTED"?window.prompt("Correct scientific name:"):null;act(()=>updateAdminObservationDisposition(selected.observation_id,value,species,"Operational expert review"));}} className="rounded border px-2 py-1 text-xs">{label(value)}</button>)}</div><button onClick={requestInformation} className="mt-3 rounded border border-amber-500 px-3 py-2 text-xs">Request additional information</button>{selected.workflow_state==="AWAITING_REPORTER_INFORMATION"&&<button onClick={prepareLink} className="ml-2 mt-3 rounded border px-3 py-2 text-xs">Prepare new private link</button>}<p className="mt-4 rounded bg-amber-50 p-3 text-xs">Operational verification does not establish ecological status, anomaly, or governed occurrence evidence.</p></article></div>
      {delivery&&<article className="rounded-xl border border-teal-200 bg-teal-50 p-5"><h3 className="font-bold">Manual reporter delivery</h3><p className="mt-2 text-sm">{delivery.message}</p><p className="mt-2 break-all rounded bg-white p-2 text-xs">{delivery.url}</p><div className="mt-3 flex gap-2"><button onClick={()=>copy(delivery.url)} className="rounded bg-teal-700 px-3 py-2 text-xs font-bold text-white">Copy link</button><button onClick={()=>copy(`${delivery.message}\n${delivery.url}`)} className="rounded border px-3 py-2 text-xs">Copy message</button></div><p className="mt-2 text-xs text-app-muted">Private reporter link. Share only through an approved channel.</p></article>}
      {detail?.reporter_responses?.length>0&&<article className="rounded-xl border bg-white p-5"><h3 className="font-bold">Reporter follow-up</h3>{detail.reporter_responses.map((r,i)=><div key={i} className="mt-3 rounded bg-slate-50 p-3 text-sm"><p>{r.response_text}</p><small>{new Date(r.created_at).toLocaleString()}</small></div>)}</article>}
      {detail?.case?.scientific_context&&<article className="rounded-xl border border-teal-200 bg-white p-5"><p className="text-xs font-bold uppercase tracking-wide text-teal-700">Early-warning / scientific context</p><h3 className="mt-1 font-bold">{label(detail.case.scientific_context.anomaly_eligibility)}</h3>{detail.case.scientific_context.eligibility_reasons?.length>0&&<ul className="mt-2 list-disc pl-5 text-sm">{detail.case.scientific_context.eligibility_reasons.map(reason=><li key={reason}>{reason}</li>)}</ul>}<p className="mt-2 text-sm">Evaluation: {label(detail.case.scientific_context.evaluation_state)}</p>{detail.case.scientific_context.current_assessment&&<div className="mt-2 rounded bg-slate-50 p-3 text-sm"><b>{label(detail.case.scientific_context.current_assessment.overall_status)}</b><p>Scientific review required: {detail.case.scientific_context.current_assessment.requires_review?"Yes":"No"}</p>{(user.is_platform_admin||user.scientific_review?.enabled)&&<a href={detail.case.scientific_context.scientific_review_url} className="mt-2 inline-block font-bold text-teal-700 underline">Open scientific assessment</a>}</div>}<p className="mt-3 text-xs text-app-muted">{detail.case.scientific_context.interpretation} Eligibility is not itself an anomaly.</p></article>}
      <article className="rounded-xl border bg-white p-5"><h3 className="font-bold">Audit history</h3><ol className="mt-3 space-y-3 border-l pl-4">{(detail?.audit_history||[]).map((event,index)=><li key={`${event.created_at}-${index}`}><p className="text-sm font-medium">{label(event.event_type)}</p><p className="text-xs text-app-muted">{new Date(event.created_at).toLocaleString()} · {event.actor_display_name}</p>{event.reason_reference&&<p className="text-xs">{event.reason_reference}</p>}</li>)}</ol></article></div>:<p className="text-app-muted">Select an observation to review.</p>}{error&&<p role="alert" className="mt-3 rounded bg-red-50 p-3 text-red-700">{error}</p>}</section>
  </main>;
}
