import { useEffect, useState } from "react";
import {
  addAdminMembership, addAdminParticipation, createAdminJurisdiction, createAdminOrganization,
  createAdminRegion, createAdminUser, getAdminJurisdictions, getAdminOrganizations,
  getAdminOverview, getAdminRegions, getAdminSpeciesPrograms, getTrustedUsers, updateAdminJurisdiction,
  updateAdminMembership, updateAdminOrganization, updateAdminParticipation,
  updateAdminRegion, updateAdminUser,
} from "../services/api";

const readable = (value) => value ? String(value).replaceAll("_", " ").toLowerCase().replace(/\b\w/g, (character) => character.toUpperCase()) : "Unavailable";

function useRegistry(loader) {
  const [state, setState] = useState({ status: "loading", data: null, error: null });
  const load = async () => { try { setState({ status: "loading", data: null, error: null }); const data = await loader(); setState({ status: "ready", data, error: null }); } catch (error) { setState({ status: "error", data: null, error: error.message }); } };
  useEffect(() => { let active = true; loader().then((data) => active && setState({ status: "ready", data, error: null })).catch((error) => active && setState({ status: "error", data: null, error: error.message })); return () => { active = false; }; }, [loader]);
  return [state, load];
}

export function AdminOverviewPage() {
  const [state, reload] = useRegistry(getAdminOverview);
  return <AdminPage title="Platform overview" description="Configuration readiness for geography, organizations, and trusted access."><LoadState state={state} retry={reload}>{state.data && <><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{Object.entries(state.data.counts).map(([key, value]) => <Metric key={key} label={readable(key)} value={value} />)}</div><section className="mt-6 rounded-xl border border-app-border bg-white p-5"><h2 className="font-bold">Configuration attention</h2>{state.data.warnings.length === 0 ? <p className="mt-3 text-sm text-app-muted">No configuration warnings detected.</p> : <div className="mt-3 divide-y divide-app-border">{state.data.warnings.map((warning, index) => <p key={`${warning.type}-${index}`} className="py-3 text-sm text-amber-900">{warning.message}</p>)}</div>}</section></>}</LoadState></AdminPage>;
}

export function SpeciesProgramsRegistryPage() {
  const [state, reload] = useRegistry(getAdminSpeciesPrograms);
  return <AdminPage title="Scientific deployments" description="Read-only registry of validated jurisdiction-specific scientific deployments for monitored species."><LoadState state={state} retry={reload}>{state.data && <RegistryList empty="No validated scientific deployments configured.">{state.data.species_programs.map((program) => { const active = program.suitability.deployments.find((item) => item.status === "ACTIVE"); return <RegistryCard key={program.id} title={program.scientific_name} subtitle={`${program.jurisdiction.name} scientific deployment · ${program.common_name || "No common name"}`} status={program.status} facts={[`Species identity: ${program.species?.id ?? "Unlinked"}`, `Suitability: ${active?.model_version || "Not configured"}`, `Monitoring Priority: ${active?.monitoring_priority?.prediction_version || "Not configured"}`]}><div className="mt-3 rounded-lg bg-slate-50 p-3 text-xs text-app-muted"><p>Suitability deployment: {program.suitability.status}</p><p>Monitoring Priority: {active?.monitoring_priority?.status || "NOT_CONFIGURED"}</p>{active?.artifact_hash && <p className="mt-1 break-all">Artifact SHA-256: {active.artifact_hash}</p>}<p className="mt-2">A species identity is shared across jurisdictions. Each jurisdiction owns its own validated scientific deployment.</p></div></RegistryCard>; })}</RegistryList>}</LoadState></AdminPage>;
}

export function RegionsRegistryPage() {
  const [state, reload] = useRegistry(getAdminRegions); const [dialog, setDialog] = useState(null);
  const save = async (values) => { if (dialog?.id) await updateAdminRegion(dialog.id, values); else await createAdminRegion(values); setDialog(null); reload(); };
  return <AdminPage title="Regions" description="Top-level geographic groupings for operational jurisdictions." action="Create region" onAction={() => setDialog({ name: "", slug: "", status: "ACTIVE" })}><LoadState state={state} retry={reload}>{state.data && <RegistryList empty="No regions configured.">{state.data.regions.map((item) => <RegistryCard key={item.id} title={item.name} subtitle={item.slug} status={item.status} facts={[`${item.jurisdiction_count} jurisdictions`, `Updated ${formatDate(item.updated_at)}`]} onSelect={() => setDialog(item)} />)}</RegistryList>}</LoadState>{dialog && <EntityDialog title={dialog.id ? "Edit region" : "Create region"} initial={dialog} fields={[field("name", "Region name"), field("slug", "Slug"), select("status", "Status", ["ACTIVE", "INACTIVE"])]} confirmStatus={Boolean(dialog.id)} onClose={() => setDialog(null)} onSave={save} />}</AdminPage>;
}

export function JurisdictionsRegistryPage() {
  const [state, reload] = useRegistry(getAdminJurisdictions); const [regions] = useRegistry(getAdminRegions); const [dialog, setDialog] = useState(null); const regionOptions = regions.data?.regions.map((item) => ({ value: item.id, label: item.name })) || [];
  const save = async (values) => { const payload = { ...values, region_id: Number(values.region_id), center_latitude: Number(values.center_latitude), center_longitude: Number(values.center_longitude), default_zoom: Number(values.default_zoom) }; if (dialog?.id) await updateAdminJurisdiction(dialog.id, payload); else await createAdminJurisdiction(payload); setDialog(null); reload(); };
  return <AdminPage title="Jurisdictions" description="Operational authority workspaces and boundary readiness." action="Create jurisdiction" onAction={() => setDialog({ region_id: regionOptions[0]?.value || "", name: "", slug: "", country_code: "", status: "ACTIVE", center_latitude: 0, center_longitude: 0, default_zoom: 7 })}><LoadState state={state} retry={reload}>{state.data && <RegistryList empty="No jurisdictions configured.">{state.data.jurisdictions.map((item) => <RegistryCard key={item.id} title={item.name} subtitle={`${item.region.name} · ${item.country_code}`} status={item.status} facts={[item.operational_boundary_configured ? "Boundary configured" : "Boundary not configured", `${item.participating_organization_count} organizations`, `${item.trusted_user_count} trusted users`]} onSelect={() => setDialog({ ...item, region_id: item.region.id })}>{item.boundaries.map((boundary) => <div key={boundary.id} className="mt-3 rounded-lg bg-slate-50 p-3 text-xs text-app-muted"><strong className="text-app-text">{readable(boundary.boundary_type)}</strong><p>{boundary.source} {boundary.source_version || ""}</p><p>{boundary.source_reference || "No source reference"}</p><p>Configuration metadata only; not represented as a legal boundary.</p></div>)}</RegistryCard>)}</RegistryList>}</LoadState>{dialog && <EntityDialog title={dialog.id ? "Edit jurisdiction" : "Create jurisdiction"} initial={dialog} fields={[select("region_id", "Region", regionOptions), field("name", "Jurisdiction name"), field("slug", "Slug"), field("country_code", "Country code"), number("center_latitude", "Map center latitude"), number("center_longitude", "Map center longitude"), number("default_zoom", "Default zoom"), select("status", "Status", ["ACTIVE", "INACTIVE"])]} confirmStatus={Boolean(dialog.id)} onClose={() => setDialog(null)} onSave={save} />}</AdminPage>;
}

export function OrganizationsRegistryPage() {
  const [state, reload] = useRegistry(getAdminOrganizations); const [jurisdictions] = useRegistry(getAdminJurisdictions); const [selectedId, setSelectedId] = useState(null); const [creating, setCreating] = useState(false); const selected = state.data?.organizations.find((item) => item.id === selectedId);
  return <AdminPage title="Organizations" description="Participating institutions in shared jurisdiction monitoring." action="Create organization" onAction={() => setCreating(true)}><LoadState state={state} retry={reload}>{state.data && <div className="grid gap-5 lg:grid-cols-[minmax(280px,38%)_minmax(0,1fr)]"><RegistryList empty="No organizations are configured. Create one when a real deployment partner is known.">{state.data.organizations.map((item) => <RegistryCard key={item.id} title={item.name} subtitle={readable(item.organization_type)} status={item.status} facts={[`${item.jurisdictions.length} jurisdictions`, `${item.memberships.length} members`]} onSelect={() => setSelectedId(item.id)} />)}</RegistryList><section className="rounded-xl border border-app-border bg-white p-5">{selected ? <OrganizationDetail item={selected} jurisdictions={jurisdictions.data?.jurisdictions || []} onChanged={reload} /> : <Empty text="Select an organization to manage participation and memberships." />}</section></div>}</LoadState>{creating && <EntityDialog title="Create organization" initial={{ name: "", slug: "", organization_type: "OTHER", status: "ACTIVE" }} fields={[field("name", "Organization name"), field("slug", "Slug"), select("organization_type", "Organization type", ["GOVERNMENT_AGENCY", "RESEARCH_INSTITUTION", "UNIVERSITY", "CONSERVATION_ORGANIZATION", "OTHER"])]} onClose={() => setCreating(false)} onSave={async (values) => { const created = await createAdminOrganization(values); setCreating(false); setSelectedId(created.id); reload(); }} />}</AdminPage>;
}

function OrganizationDetail({ item, jurisdictions, onChanged }) {
  const linked = new Set(item.jurisdictions.map((entry) => entry.id)); const available = jurisdictions.filter((entry) => !linked.has(entry.id)); const [jurisdictionId, setJurisdictionId] = useState(""); const [editing, setEditing] = useState(false); const choice = jurisdictionId || available[0]?.id || "";
  const changeStatus = async () => { const status = item.status === "ACTIVE" ? "INACTIVE" : "ACTIVE"; if (status === "INACTIVE" && !window.confirm("Deactivate this organization? Derived jurisdiction access will stop while historical records remain.")) return; await updateAdminOrganization(item.id, { status }); onChanged(); };
  return <><div className="flex flex-wrap justify-between gap-3"><div><h2 className="text-xl font-bold">{item.name}</h2><p className="text-sm text-app-muted">{readable(item.organization_type)}</p></div><div className="flex gap-2"><button onClick={() => setEditing(true)} className="rounded-lg border border-app-border px-3 py-2 text-xs font-bold">Edit</button><button onClick={changeStatus} className="rounded-lg border border-app-border px-3 py-2 text-xs font-bold">{item.status === "ACTIVE" ? "Deactivate" : "Activate"}</button></div></div><h3 className="mt-6 text-sm font-bold">Jurisdiction participation</h3><div className="mt-2 space-y-2">{item.jurisdictions.map((entry) => <div key={entry.id} className="flex items-center justify-between rounded-lg border border-app-border p-3 text-sm"><span>{entry.name} · {readable(entry.relationship_status)}</span><button onClick={async () => { const status = entry.relationship_status === "ACTIVE" ? "INACTIVE" : "ACTIVE"; if (status === "INACTIVE" && !window.confirm("Deactivate this jurisdiction participation? Operational access through it will stop.")) return; await updateAdminParticipation(entry.relationship_id, status); onChanged(); }} className="font-bold text-teal-700">{entry.relationship_status === "ACTIVE" ? "Deactivate" : "Activate"}</button></div>)}</div>{available.length > 0 && <div className="mt-3 flex gap-2"><select value={choice} onChange={(event) => setJurisdictionId(event.target.value)} className="min-w-0 flex-1 rounded-lg border border-app-border px-3 py-2 text-sm">{available.map((entry) => <option key={entry.id} value={entry.id}>{entry.name}</option>)}</select><button onClick={async () => { await addAdminParticipation(item.id, choice); onChanged(); }} className="rounded-lg bg-teal-700 px-3 py-2 text-sm font-bold text-white">Add</button></div>}<h3 className="mt-6 text-sm font-bold">Members</h3>{item.memberships.length === 0 ? <p className="mt-2 text-sm text-app-muted">No trusted users assigned.</p> : item.memberships.map((membership) => <p key={membership.id} className="mt-2 text-sm">{membership.user.display_name} · {readable(membership.role)} · {readable(membership.status)}</p>)}{editing && <EntityDialog title="Edit organization" initial={item} fields={[field("name", "Organization name"), field("slug", "Slug"), select("organization_type", "Organization type", ["GOVERNMENT_AGENCY", "RESEARCH_INSTITUTION", "UNIVERSITY", "CONSERVATION_ORGANIZATION", "OTHER"])]} onClose={() => setEditing(false)} onSave={async (values) => { await updateAdminOrganization(item.id, { name: values.name, slug: values.slug, organization_type: values.organization_type }); setEditing(false); onChanged(); }} />}</>;
}

export function UsersRegistryPage() {
  const [state, reload] = useRegistry(getTrustedUsers); const [organizations] = useRegistry(getAdminOrganizations); const [selectedId, setSelectedId] = useState(null); const [creating, setCreating] = useState(false); const selected = state.data?.users.find((item) => item.id === selectedId);
  return <AdminPage title="Trusted users" description="Provisioned accounts and organization-derived jurisdiction roles." action="Provision user" onAction={() => setCreating(true)}><LoadState state={state} retry={reload}>{state.data && <div className="grid gap-5 lg:grid-cols-[minmax(300px,40%)_minmax(0,1fr)]"><RegistryList empty="No trusted users configured.">{state.data.users.map((item) => <RegistryCard key={item.id} title={item.display_name} subtitle={item.email} status={item.status} facts={[item.is_platform_admin ? "Platform administrator" : `${item.memberships.length} memberships`, item.last_login_at ? `Last login ${formatDate(item.last_login_at)}` : "Never signed in"]} onSelect={() => setSelectedId(item.id)} />)}</RegistryList><section className="rounded-xl border border-app-border bg-white p-5">{selected ? <UserDetail item={selected} organizations={organizations.data?.organizations || []} onChanged={reload} /> : <Empty text="Select a user to manage trusted access." />}</section></div>}</LoadState>{creating && <EntityDialog title="Provision trusted user" initial={{ display_name: "", email: "", initial_password: "", status: "ACTIVE" }} fields={[field("display_name", "Display name"), field("email", "Email", "email"), field("initial_password", "Temporary password", "password")]} note="The temporary password is submitted once, hashed immediately, and cannot be retrieved later. Deliver it securely." onClose={() => setCreating(false)} onSave={async (values) => { const created = await createAdminUser(values); setCreating(false); setSelectedId(created.id); reload(); }} />}</AdminPage>;
}

function UserDetail({ item, organizations, onChanged }) {
  const memberships = new Set(item.memberships.map((membership) => membership.organization.id)); const available = organizations.filter((organization) => !memberships.has(organization.id)); const [organizationId, setOrganizationId] = useState(""); const [role, setRole] = useState("VIEWER"); const choice = organizationId || available[0]?.id || "";
  return <><div className="flex flex-wrap justify-between gap-3"><div><h2 className="text-xl font-bold">{item.display_name}</h2><p className="text-sm text-app-muted">{item.email}</p>{item.is_platform_admin && <p className="mt-2 text-xs font-bold text-teal-700">Platform administrator · managed through controlled bootstrap</p>}</div>{!item.is_platform_admin && <button onClick={async () => { const status = item.status === "ACTIVE" ? "INACTIVE" : "ACTIVE"; if (status === "INACTIVE" && !window.confirm("Deactivate this account and revoke its sessions? Historical attribution will remain.")) return; await updateAdminUser(item.id, { status }); onChanged(); }} className="rounded-lg border border-app-border px-3 py-2 text-xs font-bold">{item.status === "ACTIVE" ? "Deactivate" : "Activate"}</button>}</div><h3 className="mt-6 text-sm font-bold">Organization memberships</h3>{item.memberships.map((membership) => <div key={membership.id} className="mt-2 grid gap-2 rounded-lg border border-app-border p-3 sm:grid-cols-[1fr_130px_110px]"><span className="text-sm font-semibold">{membership.organization.name}</span><select value={membership.role} onChange={async (event) => { await updateAdminMembership(membership.id, { role: event.target.value }); onChanged(); }} className="rounded border border-app-border px-2 py-1 text-sm">{["VIEWER", "REVIEWER", "MANAGER"].map((value) => <option key={value}>{value}</option>)}</select><button onClick={async () => { const status = membership.status === "ACTIVE" ? "INACTIVE" : "ACTIVE"; if (status === "INACTIVE" && !window.confirm("Deactivate this membership? Derived jurisdiction access will stop.")) return; await updateAdminMembership(membership.id, { status }); onChanged(); }} className="text-xs font-bold text-teal-700">{membership.status === "ACTIVE" ? "Deactivate" : "Activate"}</button></div>)}{available.length > 0 && <div className="mt-3 grid gap-2 sm:grid-cols-[1fr_130px_auto]"><select value={choice} onChange={(event) => setOrganizationId(event.target.value)} className="rounded-lg border border-app-border px-3 py-2 text-sm">{available.map((organization) => <option key={organization.id} value={organization.id}>{organization.name}</option>)}</select><select value={role} onChange={(event) => setRole(event.target.value)} className="rounded-lg border border-app-border px-3 py-2 text-sm">{["VIEWER", "REVIEWER", "MANAGER"].map((value) => <option key={value}>{value}</option>)}</select><button onClick={async () => { await addAdminMembership(item.id, { organization_id: Number(choice), role }); onChanged(); }} className="rounded-lg bg-teal-700 px-3 py-2 text-sm font-bold text-white">Add membership</button></div>}</>;
}

function AdminPage({ title, description, action, onAction, children }) { return <div className="mx-auto max-w-[1450px]"><header className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[.15em] text-teal-700">Platform administration</p><h1 className="mt-1 text-3xl font-bold">{title}</h1><p className="mt-2 text-sm text-app-muted">{description}</p></div>{action && <button onClick={onAction} className="rounded-lg bg-teal-700 px-4 py-2.5 text-sm font-bold text-white">{action}</button>}</header><div className="mt-6">{children}</div></div>; }
function LoadState({ state, retry, children }) { if (state.status === "loading") return <div className="rounded-xl border border-app-border bg-white p-10 text-center text-app-muted">Loading configurationâ€¦</div>; if (state.status === "error") return <div><ErrorBox text={state.error} /><button onClick={retry} className="mt-3 rounded-lg border border-app-border px-3 py-2 text-sm font-bold">Try again</button></div>; return children; }
function RegistryList({ empty, children }) { const entries = Array.isArray(children) ? children.filter(Boolean) : children ? [children] : []; return <div className="overflow-hidden rounded-xl border border-app-border bg-white">{entries.length ? entries : <Empty text={empty} />}</div>; }
function RegistryCard({ title, subtitle, status, facts, onSelect, children }) { return <article className="border-b border-app-border p-4 last:border-0"><button onClick={onSelect} className="w-full text-left"><div className="flex items-start justify-between gap-3"><div><strong className="text-sm">{title}</strong><p className="text-xs text-app-muted">{subtitle}</p></div><Status value={status} /></div><p className="mt-3 text-xs text-app-muted">{facts.join(" · ")}</p></button>{children}</article>; }
function Metric({ label, value }) { return <div className="rounded-xl border border-app-border bg-white p-5"><span className="text-xs text-app-muted">{label}</span><strong className="mt-1 block text-3xl text-teal-700">{value}</strong></div>; }
function Empty({ text }) { return <div className="p-10 text-center text-sm text-app-muted">{text}</div>; }
function ErrorBox({ text }) { return <div className="mt-3 rounded-lg border border-red-200 bg-red-50 p-3 text-sm text-red-700">{text}</div>; }
function Status({ value }) { return <span className={`rounded-full px-2 py-1 text-[11px] font-bold ${value === "ACTIVE" ? "bg-teal-50 text-teal-700" : "bg-slate-100 text-slate-600"}`}>{readable(value)}</span>; }
function formatDate(value) { return value ? new Date(value).toLocaleDateString() : "Unavailable"; }
function field(name, label, type = "text") { return { name, label, type }; }
function number(name, label) { return field(name, label, "number"); }
function select(name, label, options) { return { name, label, type: "select", options }; }

function EntityDialog({ title, initial, fields, note, confirmStatus, onClose, onSave }) {
  const [values, setValues] = useState(initial); const [saving, setSaving] = useState(false); const [error, setError] = useState(null);
  async function submit(event) { event.preventDefault(); if (confirmStatus && initial.status === "ACTIVE" && values.status === "INACTIVE" && !window.confirm("Deactivate this configuration? Historical records will remain, but operational access may stop.")) return; setSaving(true); setError(null); try { await onSave(values); } catch (saveError) { setError(saveError.message); } finally { setSaving(false); } }
  return <div className="fixed inset-0 z-[1700] grid place-items-center bg-slate-950/45 p-3"><form onSubmit={submit} className="max-h-[92vh] w-full max-w-xl overflow-y-auto rounded-2xl bg-white p-6 shadow-2xl"><div className="flex justify-between"><h2 className="text-xl font-bold">{title}</h2><button type="button" onClick={onClose} aria-label="Close">Ã—</button></div>{note && <p className="mt-3 rounded-lg bg-amber-50 p-3 text-xs text-amber-900">{note}</p>}<div className="mt-5 grid gap-4 sm:grid-cols-2">{fields.map((item) => <label key={item.name} className="text-sm font-bold">{item.label}{item.type === "select" ? <select value={values[item.name]} onChange={(event) => setValues({ ...values, [item.name]: event.target.value })} className="mt-1 w-full rounded-lg border border-app-border p-2.5 font-normal">{item.options.map((option) => { const entry = typeof option === "object" ? option : { value: option, label: readable(option) }; return <option key={entry.value} value={entry.value}>{entry.label}</option>; })}</select> : <input required type={item.type} step={item.type === "number" ? "any" : undefined} value={values[item.name]} onChange={(event) => setValues({ ...values, [item.name]: event.target.value })} className="mt-1 w-full rounded-lg border border-app-border p-2.5 font-normal" />}</label>)}</div>{error && <ErrorBox text={error} />}<div className="mt-6 flex justify-end gap-2"><button type="button" onClick={onClose} className="rounded-lg border border-app-border px-4 py-2 text-sm font-bold">Cancel</button><button disabled={saving} className="rounded-lg bg-teal-700 px-4 py-2 text-sm font-bold text-white">{saving ? "Savingâ€¦" : "Save"}</button></div></form></div>;
}
