import { useEffect, useState } from "react";
import { createSystemBackup, getSystemStatus } from "../services/api";

export default function AdminSystemStatusPage(){
  const [data,setData]=useState(null),[error,setError]=useState(""),[busy,setBusy]=useState(false);
  const load=()=>getSystemStatus().then(setData).catch((e)=>setError(e.message));
  useEffect(load,[]);
  if(error)return <div role="alert" className="rounded-xl border border-red-200 bg-red-50 p-5 text-red-800"><h1 className="font-bold">System status unavailable</h1><p className="mt-1 text-sm">{error}</p><button onClick={()=>{setError("");load();}} className="mt-3 rounded bg-teal-700 px-3 py-2 text-sm font-bold text-white">Retry</button></div>;
  if(!data)return <p className="p-6 text-sm text-slate-600">Loading controlled system status…</p>;
  const checks=data.health?.checks||{};
  return <div className="mx-auto max-w-6xl space-y-6 p-6"><header><p className="text-xs font-bold uppercase tracking-widest text-teal-700">Platform operations</p><h1 className="mt-1 text-3xl font-bold">System status</h1><p className="mt-2 text-sm text-slate-600">Safe deployment health and durable scientific-event operations. No scientific automation is enabled here implicitly.</p><p className="mt-2 text-sm"><strong>Database:</strong> {data.health?.database_backend === "postgresql" ? "PostgreSQL" : "SQLite"} · <strong>Connection:</strong> {checks.database?.ok ? "Healthy" : "Unavailable"} · <strong>Migration:</strong> {checks.migrations?.ok ? "Current" : "Pending"}</p></header>{data.demo&&<div className="rounded-lg bg-amber-100 p-3 font-bold text-amber-900">DEMONSTRATION ENVIRONMENT</div>}<section className="grid gap-3 md:grid-cols-3">{Object.entries(checks).map(([name,value])=><article key={name} className="rounded-xl border bg-white p-4"><span className="text-xs uppercase text-slate-500">{name}</span><strong className={`mt-1 block ${value.ok?"text-teal-700":"text-red-700"}`}>{value.ok?"Available":"Attention required"}</strong></article>)}</section><section className="grid gap-5 lg:grid-cols-2"><article className="rounded-xl border bg-white p-5"><h2 className="font-bold">Scientific event queue</h2><dl className="mt-3 space-y-2 text-sm">{Object.entries(data.scientific_event_queue||{}).map(([key,value])=><div key={key} className="flex justify-between border-b py-2"><dt>{key}</dt><dd className="font-bold">{value}</dd></div>)}</dl><p className="mt-4 text-xs text-slate-500">Worker: {data.worker.enabled?"enabled":"disabled"} · Global automatic evaluation gate: {data.automatic_scientific_evaluation_global_gate?"enabled":"disabled"}</p></article><article className="rounded-xl border bg-white p-5"><h2 className="font-bold">Backup</h2><p className="mt-2 text-sm text-slate-600">Creates a database-consistent, hashed backup in controlled storage.</p>{data.last_successful_backup?<p className="mt-3 text-sm">Last valid backup: <strong>{data.last_successful_backup.backup_identity}</strong></p>:<p className="mt-3 text-sm text-amber-700">No managed backup recorded.</p>}<button disabled={busy} onClick={async()=>{setBusy(true);try{await createSystemBackup();await load();}catch(e){setError(e.message)}finally{setBusy(false)}}} className="mt-4 rounded bg-teal-700 px-4 py-2 text-sm font-bold text-white disabled:opacity-50">{busy?"Creating…":"Create backup"}</button></article></section></div>;
}
