import { useEffect, useMemo, useState } from "react";
import { getAdminJurisdictions, getScientificScalingInventory, getScientificScalingMatrix, getScientificScalingSummary, getScientificScalingWorkQueue } from "../services/api";
import VisualCorpusPanel from "../components/admin/VisualCorpusPanel";
const dimensions=["taxonomy","occurrence","ecology","public_directory","imagery","identification","environmental","suitability","early_warning"];
const groups=["FISH","ALGAE_SEAWEED","CRUSTACEANS","MOLLUSCS","CNIDARIANS","ECHINODERMS","OTHER"],states=["READY","PARTIAL","BLOCKED","REVIEW_REQUIRED","UNKNOWN","NOT_APPLICABLE"];
const label=(v)=>String(v||"Unknown").replaceAll("_"," ").toLowerCase().replace(/\b\w/g,(c)=>c.toUpperCase());
const tone={READY:"bg-teal-50 text-teal-700",PARTIAL:"bg-sky-50 text-sky-700",BLOCKED:"bg-red-50 text-red-700",REVIEW_REQUIRED:"bg-amber-50 text-amber-800",UNKNOWN:"bg-slate-100 text-slate-600"};
function Badge({value}){return <span className={`inline-flex rounded-full px-2 py-1 text-[10px] font-bold ${tone[value]||"bg-slate-100 text-slate-700"}`}>{label(value)}</span>}
function Metric({title,value,note}){return <article className="rounded-xl border border-app-border bg-white p-4"><p className="text-[11px] font-bold uppercase tracking-wide text-app-muted">{title}</p><strong className="mt-2 block text-2xl">{value??"—"}</strong>{note&&<p className="mt-1 text-xs text-app-muted">{note}</p>}</article>}
export default function AdminScientificReadinessPage(){
 const [jurisdictions,setJurisdictions]=useState([]),[regionId,setRegionId]=useState(""),[jurisdictionId,setJurisdictionId]=useState("");const [taxonGroup,setTaxonGroup]=useState(""),[dimension,setDimension]=useState(""),[readinessState,setReadinessState]=useState(""),[search,setSearch]=useState("");const [page,setPage]=useState(1),[summary,setSummary]=useState(null),[inventory,setInventory]=useState(null),[matrix,setMatrix]=useState(null),[queue,setQueue]=useState(null),[selected,setSelected]=useState(null),[error,setError]=useState(""),[loading,setLoading]=useState(true),[tab,setTab]=useState("matrix");
 const regionJurisdictions=useMemo(()=>jurisdictions.filter((j)=>String(j.region?.id)===String(regionId)),[jurisdictions,regionId]);
 useEffect(()=>{getAdminJurisdictions().then((data)=>{const rows=data.jurisdictions||[];setJurisdictions(rows);setRegionId(String(rows[0]?.region?.id||""))}).catch((e)=>setError(e.message))},[]);
 useEffect(()=>{if(!regionId)return;let active=true;const params={jurisdiction_id:jurisdictionId,taxon_group:taxonGroup,dimension,readiness_state:readinessState,search,page,page_size:50};Promise.all([getScientificScalingSummary(regionId),getScientificScalingInventory(regionId),getScientificScalingMatrix(regionId,params),getScientificScalingWorkQueue(regionId,{jurisdiction_id:jurisdictionId})]).then(([s,i,m,q])=>{if(active){setSummary(s);setInventory(i);setMatrix(m);setQueue(q);setSelected(null)}}).catch((e)=>active&&setError(e.message)).finally(()=>active&&setLoading(false));return()=>{active=false}},[regionId,jurisdictionId,taxonGroup,dimension,readinessState,search,page]);
 return <div className="mx-auto max-w-[1600px] space-y-5"><header><p className="text-xs font-bold uppercase tracking-[.15em] text-teal-700">Platform science administration</p><h1 className="mt-1 text-3xl font-bold">Caribbean scientific readiness</h1><p className="mt-2 max-w-4xl text-sm text-app-muted">Nine independent governed dimensions. No overall score or readiness percentage is calculated.</p></header>{error&&<p className="rounded-lg border border-red-200 bg-red-50 p-3 text-sm text-red-700">{error}</p>}
 <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-6"><Metric title="Inventory" value={inventory?.total_governed_inventory} note={`${inventory?.summary?.onboarded||0} onboarded`}/><Metric title="Governed taxa" value={summary?.governed_taxa}/><Metric title="Combinations" value={summary?.combinations}/><Metric title="Occurrence ready" value={summary?.readiness?.occurrence?.READY||0}/><Metric title="Identification ready" value={summary?.readiness?.identification?.READY||0}/><Metric title="Directory available" value={summary?.governed_directory_combinations||0}/></section>
 <section className="rounded-xl border border-app-border bg-white p-4"><div className="grid gap-3 md:grid-cols-3 xl:grid-cols-6"><Select title="Region" value={regionId} onChange={(v)=>{setRegionId(v);setJurisdictionId("");setPage(1)}} options={[...new Map(jurisdictions.map((j)=>[j.region.id,j.region])).values()].map((r)=>[r.id,r.name])}/><Select title="Jurisdiction" value={jurisdictionId} onChange={(v)=>{setJurisdictionId(v);setPage(1)}} empty="All onboarded" options={regionJurisdictions.map((j)=>[j.id,j.name])}/><Select title="Taxonomic group" value={taxonGroup} onChange={(v)=>{setTaxonGroup(v);setPage(1)}} empty="All groups" options={groups.map((g)=>[g,label(g)])}/><Select title="Dimension" value={dimension} onChange={(v)=>{setDimension(v);if(!v)setReadinessState("");setPage(1)}} empty="All dimensions" options={dimensions.map((d)=>[d,label(d)])}/><Select title="Readiness state" value={readinessState} onChange={(v)=>{setReadinessState(v);setPage(1)}} empty="All states" disabled={!dimension} options={states.map((s)=>[s,label(s)])}/><label className="text-xs font-bold">Search<input value={search} onChange={(e)=>setSearch(e.target.value)} className="mt-1 w-full rounded-lg border border-app-border px-3 py-2 text-sm font-normal" placeholder="Taxon or jurisdiction"/></label></div></section>
 <nav className="flex gap-2 overflow-x-auto border-b border-app-border"><Tab active={tab==="matrix"} onClick={()=>setTab("matrix")}>Readiness matrix</Tab><Tab active={tab==="queue"} onClick={()=>setTab("queue")}>Work queue ({queue?.count||0})</Tab><Tab active={tab==="inventory"} onClick={()=>setTab("inventory")}>Jurisdiction inventory</Tab><Tab active={tab==="visual"} onClick={()=>setTab("visual")}>Visual corpus</Tab></nav>
 {loading?<div className="rounded-xl border border-app-border bg-white p-12 text-center text-sm text-app-muted">Loading governed configuration…</div>:tab==="matrix"?<Matrix cells={matrix?.items||[]} onSelect={setSelected}/>:tab==="queue"?<WorkQueue items={queue?.items||[]}/>:tab==="visual"?<VisualCorpusPanel/>:<Inventory items={inventory?.items||[]}/>} {tab==="matrix"&&matrix&&<div className="flex items-center justify-between text-sm"><span>{matrix.total} combinations · page {matrix.page}</span><div className="flex gap-2"><button disabled={page===1} onClick={()=>setPage((p)=>p-1)} className="rounded border px-3 py-1 disabled:opacity-40">Previous</button><button disabled={page*matrix.page_size>=matrix.total} onClick={()=>setPage((p)=>p+1)} className="rounded border px-3 py-1 disabled:opacity-40">Next</button></div></div>}{selected&&<Detail cell={selected} onClose={()=>setSelected(null)}/>}<p className="rounded-lg bg-slate-50 p-3 text-xs text-app-muted">Regional identification support does not establish jurisdiction presence. Occurrence evidence does not establish ecological status. Readiness does not indicate an anomaly.</p></div>
}
function Select({title,value,onChange,options,empty,disabled}){return <label className="text-xs font-bold">{title}<select disabled={disabled} value={value} onChange={(e)=>onChange(e.target.value)} className="mt-1 w-full rounded-lg border border-app-border px-3 py-2 text-sm font-normal disabled:opacity-50">{empty!==undefined&&<option value="">{empty}</option>}{options.map(([v,n])=><option key={v} value={v}>{n}</option>)}</select></label>}
function Tab({active,onClick,children}){return <button onClick={onClick} className={`px-4 py-3 text-sm font-bold ${active?"border-b-2 border-teal-600 text-teal-700":"text-app-muted"}`}>{children}</button>}
function Matrix({cells,onSelect}){return <section className="overflow-x-auto rounded-xl border border-app-border bg-white"><table className="min-w-[1500px] w-full text-left text-sm"><thead className="bg-slate-50 text-[10px] uppercase text-app-muted"><tr><th className="px-4 py-3">Jurisdiction × taxon</th>{dimensions.map((n)=><th key={n} className="px-3 py-3">{label(n)}</th>)}</tr></thead><tbody className="divide-y divide-app-border">{cells.map((cell)=><tr key={`${cell.jurisdiction.id}:${cell.taxon.id}`} onClick={()=>onSelect(cell)} className="cursor-pointer hover:bg-teal-50/40"><td className="px-4 py-3"><strong>{cell.jurisdiction.name}</strong><span className="block text-xs italic text-app-muted">{cell.taxon.scientific_name}</span><span className="text-[10px] text-app-muted">{label(cell.taxon.descriptive_group)}</span></td>{dimensions.map((n)=><td key={n} className="px-3 py-3"><Badge value={cell.dimensions[n].state}/></td>)}</tr>)}</tbody></table>{!cells.length&&<p className="p-10 text-center text-sm text-app-muted">No governed combinations match these filters.</p>}</section>}
function WorkQueue({items}){return <section className="grid gap-3 lg:grid-cols-2">{items.map((item,index)=><article key={`${item.category}:${index}`} className="rounded-xl border border-app-border bg-white p-4"><p className="text-[10px] font-bold uppercase text-teal-700">{label(item.category)}</p><h3 className="mt-1 font-bold">{item.jurisdiction.name} · <i>{item.taxon.scientific_name}</i></h3><p className="mt-2 text-sm">{item.reason}</p></article>)}</section>}
function Inventory({items}){return <section className="grid gap-2 md:grid-cols-3">{items.map((item)=><article key={item.canonical_identifier} className="rounded-lg border border-app-border bg-white p-4"><div className="flex justify-between"><strong>{item.canonical_name}</strong><Badge value={item.state}/></div><p className="text-xs text-app-muted">{item.canonical_identifier}</p></article>)}</section>}
function Detail({cell,onClose}){return <aside className="fixed inset-y-0 right-0 z-[70] w-full max-w-xl overflow-y-auto border-l border-app-border bg-white p-6 shadow-2xl"><button onClick={onClose} className="float-right rounded border px-3 py-1">Close</button><p className="text-xs font-bold uppercase text-teal-700">Combination detail</p><h2 className="mt-2 text-2xl font-bold">{cell.jurisdiction.name}</h2><p className="italic text-app-muted">{cell.taxon.scientific_name}</p><div className="mt-6 space-y-3">{dimensions.map((name)=><article key={name} className="rounded-lg border p-4"><div className="flex justify-between"><strong>{label(name)}</strong><Badge value={cell.dimensions[name].state}/></div><p className="mt-2 text-sm text-slate-600">{cell.dimensions[name].reason}</p></article>)}</div></aside>}
