import { useEffect, useState } from "react";
import { applyAdminTaxonomy, applyAdminTaxonomyBatch, applyLocalTaxonCandidateBatch, approveAdminTaxonomy, approveAdminTaxonomyBatch, approveLocalTaxonCandidateBatch, getAdminRegions, getAdminTaxa, getAdminTaxonomyHistory, prepareAdminTaxonomy, prepareAdminTaxonomyBulk } from "../services/api";
import RegionalTaxonManifestPanel from "../components/admin/RegionalTaxonManifestPanel";

const readable = (value) => String(value || "Unavailable").replaceAll("_", " ").toLowerCase().replace(/\b\w/g, (character) => character.toUpperCase());

export default function AdminTaxonomyPage() {
  const [taxa, setTaxa] = useState([]), [regions, setRegions] = useState([]), [taxonId, setTaxonId] = useState(""), [regionId, setRegionId] = useState("");
  const [prep, setPrep] = useState(null), [history, setHistory] = useState([]), [busy, setBusy] = useState(false), [error, setError] = useState(null);
  const [candidateText, setCandidateText] = useState(""), [bulkResults, setBulkResults] = useState([]), [selected, setSelected] = useState(new Set());

  useEffect(() => { Promise.all([getAdminTaxa(), getAdminRegions()]).then(([taxaData, regionData]) => { setTaxa(taxaData.taxa || []); setRegions(regionData.regions || []); setTaxonId(String(taxaData.taxa?.[0]?.id || "")); setRegionId(String(regionData.regions?.[0]?.id || "")); }).catch((requestError) => setError(requestError.message)); }, []);
  async function loadHistory(id = taxonId) { if (!id) return; const data = await getAdminTaxonomyHistory(id); setHistory(data.history || []); if (data.history?.[0]) setPrep(data.history[0]); }
  async function prepare() { if (busy) return; setBusy(true); setError(null); try { setPrep(await prepareAdminTaxonomy(taxonId, regionId)); await loadHistory(); } catch (requestError) { setError(requestError.message); } finally { setBusy(false); } }
  async function approve() { if (busy || !window.confirm(`Approve ${prep.proposed_scientific_name} from ${prep.provider}? This is taxonomy governance only.`)) return; const reference = window.prompt("Approval reference:", `taxonomy-review-${new Date().toISOString()}`); if (!reference) return; setBusy(true); try { setPrep(await approveAdminTaxonomy(prep.id, prep.preparation_fingerprint, reference)); await loadHistory(); } catch (requestError) { setError(requestError.message); } finally { setBusy(false); } }
  async function apply() { if (busy || !window.confirm("Apply this reviewed taxonomy identity and Caribbean registry entry? No jurisdiction science will be created.")) return; setBusy(true); try { await applyAdminTaxonomy(prep.id); await loadHistory(); } catch (requestError) { setError(requestError.message); } finally { setBusy(false); } }

  const candidates = () => candidateText.split(/\r?\n/).map((value) => value.trim()).filter(Boolean).map((submitted_scientific_name) => ({ submitted_scientific_name, candidate_source: "ADMIN_SUBMISSION", discovery_method: "EXPLICIT_NAME" }));
  async function bulk(dryRun) {
    const inputs = dryRun ? candidates() : candidates().filter((candidate) => selected.has(candidate.submitted_scientific_name));
    if (busy || !inputs.length) return;
    setBusy(true); setError(null);
    try { const data = await prepareAdminTaxonomyBulk(regionId, inputs, dryRun); const results = data.results || []; setBulkResults(results); setSelected(new Set(results.filter((result) => dryRun ? ["CREATE_PREPARATION", "CREATE_LOCAL_TAXON_CANDIDATE"].includes(result.status) : result.status === "READY_FOR_REVIEW").map((result) => dryRun ? result.candidate.submitted_scientific_name : (result.local_taxon_candidate_id || result.preparation_id)))); }
    catch (requestError) { setError(requestError.message); } finally { setBusy(false); }
  }
  async function approveSelected() {
    if (![...selected].some(Number.isInteger)) return; const reference = window.prompt("Batch approval reference:"); if (!reference) return;
    const localIds = bulkResults.filter((result) => result.local_taxon_candidate_id && selected.has(result.local_taxon_candidate_id)).map((result) => result.local_taxon_candidate_id);
    const preparationIds = bulkResults.filter((result) => result.preparation_id && selected.has(result.preparation_id)).map((result) => result.preparation_id);
    setBusy(true); try { const responses = await Promise.all([preparationIds.length ? approveAdminTaxonomyBatch(preparationIds, reference) : null, localIds.length ? approveLocalTaxonCandidateBatch(localIds, reference) : null]); const results = responses.flatMap((response) => response?.results || []); setBulkResults(results); setSelected(new Set(results.filter((result) => result.status === "APPROVED").map((result) => result.candidate_id || result.preparation_id))); } catch (requestError) { setError(requestError.message); } finally { setBusy(false); }
  }
  async function applySelected() {
    if (![...selected].some(Number.isInteger) || !window.confirm("Apply selected approved taxonomy records? Regional membership creates no jurisdiction science.")) return;
    const localIds = bulkResults.filter((result) => result.candidate_id && selected.has(result.candidate_id)).map((result) => result.candidate_id);
    const preparationIds = bulkResults.filter((result) => result.preparation_id && selected.has(result.preparation_id)).map((result) => result.preparation_id);
    setBusy(true); try { const responses = await Promise.all([preparationIds.length ? applyAdminTaxonomyBatch(preparationIds) : null, localIds.length ? applyLocalTaxonCandidateBatch(localIds) : null]); setBulkResults(responses.flatMap((response) => response?.results || [])); setSelected(new Set()); } catch (requestError) { setError(requestError.message); } finally { setBusy(false); }
  }

  return <div className="mx-auto max-w-[1250px]">
    <p className="text-xs font-bold uppercase tracking-[.15em] text-teal-700">Platform administration</p><h1 className="mt-1 text-3xl font-bold">Taxonomy governance</h1><p className="mt-2 text-sm text-app-muted">Resolve taxonomy through a controlled authoritative-provider workflow. No species programs or jurisdiction evidence are created.</p>{error && <p className="mt-4 rounded-lg border border-red-200 bg-red-50 p-3 text-sm text-red-700">{error}</p>}
    <section className="mt-6 grid gap-3 rounded-xl border border-app-border bg-white p-5 md:grid-cols-[1fr_1fr_auto]">
      <label className="text-xs font-bold">Existing local taxon<select value={taxonId} onChange={(event) => { setTaxonId(event.target.value); setPrep(null); }} className="mt-1 block w-full rounded-lg border border-app-border px-3 py-2 text-sm font-normal">{taxa.map((taxon) => <option key={taxon.id} value={taxon.id}>{taxon.canonical_scientific_name}</option>)}</select></label>
      <label className="text-xs font-bold">Regional registry<select value={regionId} onChange={(event) => setRegionId(event.target.value)} className="mt-1 block w-full rounded-lg border border-app-border px-3 py-2 text-sm font-normal">{regions.map((region) => <option key={region.id} value={region.id}>{region.name}</option>)}</select></label>
      <button disabled={!taxonId || !regionId || busy} onClick={prepare} className="self-end rounded-lg bg-teal-700 px-4 py-2 text-sm font-bold text-white disabled:opacity-40">{busy ? "Working…" : "Prepare taxonomy"}</button>
    </section>
    <RegionalTaxonManifestPanel regions={regions} />
    <section className="mt-5 rounded-xl border border-app-border bg-white p-5">
      <h2 className="font-bold">Regional candidate batch</h2><p className="mt-1 text-xs text-app-muted">Enter one scientific name per line. Unseen authoritative taxa become governed local candidates and do not create Species records until approved and applied.</p>
      <textarea value={candidateText} onChange={(event) => setCandidateText(event.target.value)} rows="4" placeholder={'Pterois volitans\nAnother reviewed candidate'} className="mt-3 w-full rounded-lg border border-app-border p-3 text-sm" />
      <div className="mt-3 flex flex-wrap gap-2"><button disabled={busy || !candidateText.trim()} onClick={() => bulk(true)} className="rounded-lg border border-app-border px-3 py-2 text-sm font-bold">Dry run</button><button disabled={busy || ![...selected].some((value) => typeof value === "string")} onClick={() => bulk(false)} className="rounded-lg bg-teal-700 px-3 py-2 text-sm font-bold text-white disabled:opacity-40">Prepare eligible</button><button disabled={busy || ![...selected].some(Number.isInteger)} onClick={approveSelected} className="rounded-lg bg-teal-700 px-3 py-2 text-sm font-bold text-white disabled:opacity-40">Approve selected</button><button disabled={busy || ![...selected].some(Number.isInteger)} onClick={applySelected} className="rounded-lg bg-slate-900 px-3 py-2 text-sm font-bold text-white disabled:opacity-40">Apply selected</button></div>
      {bulkResults.length > 0 && <div className="mt-4 divide-y divide-app-border">{bulkResults.map((result, index) => { const key = result.local_taxon_candidate_id || result.candidate_id || result.preparation_id || result.candidate?.submitted_scientific_name; return <div key={index} className="grid gap-2 py-3 text-xs sm:grid-cols-[28px_1fr_180px]"><input type="checkbox" disabled={!(["CREATE_PREPARATION", "CREATE_LOCAL_TAXON_CANDIDATE", "READY_FOR_REVIEW", "APPROVED"].includes(result.status))} checked={selected.has(key)} onChange={() => setSelected((values) => { const next = new Set(values); next.has(key) ? next.delete(key) : next.add(key); return next; })} /><div><strong>{result.candidate?.submitted_scientific_name || result.scientific_name || `${result.candidate_id ? "Local candidate" : "Preparation"} ${result.candidate_id || result.preparation_id}`}</strong><p className="text-app-muted">{result.resolution?.canonical_scientific_name || result.reason || ""} {result.resolution?.authoritative_identifier || ""}</p></div><strong>{readable(result.status)}</strong></div>; })}</div>}
      <p className="mt-4 rounded-lg bg-amber-50 p-3 text-xs text-amber-900">Regional taxonomy approval does not create jurisdiction occurrence, ecological-status, model, training, or anomaly state.</p>
    </section>
    {prep && <section className="mt-5 rounded-xl border border-app-border bg-white p-5"><div className="flex justify-between gap-3"><div><h2 className="text-xl font-bold italic">{prep.proposed_scientific_name}</h2><p className="text-sm text-app-muted">{prep.provider} · {prep.authoritative_identifier_scheme} {prep.authoritative_identifier}</p></div><strong className="text-sm text-teal-700">{readable(prep.workflow_status)}</strong></div><div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{[["Reconciliation", prep.reconciliation_result], ["Rank", prep.proposed_rank], ["Accepted status", prep.proposed_accepted_name_status], ["Authorship", prep.proposed_authorship], ["Parent", prep.proposed_parent_name], ["Artifact SHA-256", prep.raw_artifact_sha256]].map(([key, value]) => <div key={key} className="rounded-lg bg-slate-50 p-3"><p className="text-[10px] font-bold uppercase text-app-muted">{key}</p><p className="mt-1 break-all text-xs">{value || "Unavailable"}</p></div>)}</div>{prep.limitations?.map((limitation) => <p key={limitation} className="mt-3 text-xs text-amber-800">{limitation}</p>)}<p className="mt-4 rounded-lg border border-amber-200 bg-amber-50 p-3 text-xs text-amber-900">Applying enriches taxonomy and regional inventory only. It does not establish occurrence, ecology, models, or anomaly readiness in any jurisdiction.</p><div className="mt-4 flex justify-end gap-2">{prep.workflow_status === "READY_FOR_REVIEW" && <button disabled={busy} onClick={approve} className="rounded-lg bg-teal-700 px-4 py-2 text-sm font-bold text-white">Approve</button>}{prep.workflow_status === "APPROVED" && <button disabled={busy} onClick={apply} className="rounded-lg bg-slate-900 px-4 py-2 text-sm font-bold text-white">Apply taxonomy</button>}</div></section>}
    {history.length > 0 && <section className="mt-5 rounded-xl border border-app-border bg-white p-5"><h2 className="font-bold">Taxonomy history</h2>{history.map((item) => <button key={item.id} onClick={() => setPrep(item)} className="mt-2 block w-full rounded-lg border border-app-border p-3 text-left text-sm">#{item.id} · {readable(item.workflow_status)} · {item.provider} · {item.authoritative_identifier}</button>)}</section>}
  </div>;
}
