import { useEffect, useMemo, useState } from "react";
import { getAnalyticsSummary, getMapObservations, getMonitoringPriorityGrid, getMonitoringPriorityFreshness } from "../services/api";
import { useJurisdiction } from "../geography/JurisdictionContext";

const readable = (value) => value ? String(value).replaceAll("_", " ").toLowerCase().replace(/\b\w/g, (c) => c.toUpperCase()) : "Unavailable";

export default function OverviewPage({ onNavigate }) {
  const { activeRegion, activeJurisdiction, jurisdiction } = useJurisdiction();
  const hasPriority = jurisdiction?.capabilities?.monitoring_priority;
  const [state, setState] = useState({ loading: true, summary: null, observations: [], priorities: [], freshness: null, hasErrors: false });
  useEffect(() => {
    let active = true;
    const scope = { region: activeRegion, jurisdiction: activeJurisdiction };
    const optionalPriority = hasPriority ? [getMonitoringPriorityGrid(scope), getMonitoringPriorityFreshness(scope)] : [Promise.resolve(null), Promise.resolve(null)];
    Promise.allSettled([getAnalyticsSummary(scope), getMapObservations(scope), ...optionalPriority]).then((results) => {
      if (!active) return;
      const [summary, observations, priorities, freshness] = results;
      setState({ loading: false, summary: summary.status === "fulfilled" ? summary.value : null, observations: observations.status === "fulfilled" ? observations.value.markers || [] : [], priorities: priorities.status === "fulfilled" ? priorities.value.cells || [] : [], freshness: freshness.status === "fulfilled" ? freshness.value : null, hasErrors: results.some((r) => r.status === "rejected") });
    });
    return () => { active = false; };
  }, [activeJurisdiction, activeRegion, hasPriority]);
  const topPriority = useMemo(() => [...state.priorities].filter((cell) => cell.monitoring_priority_score != null).sort((a, b) => b.monitoring_priority_score - a.monitoring_priority_score)[0], [state.priorities]);
  const verified = state.observations.filter((item) => ["CONFIRMED", "CORRECTED"].includes(item.verification_status)).length;
  const kpis = [["Observations", state.summary?.total_observations ?? state.observations.length, "text-teal-700"], ["Pending review", state.summary?.pending_review, "text-amber-600"], ["Verified reports", verified, "text-blue-700"], [hasPriority ? "High priority areas" : "Scientific deployment", hasPriority ? state.priorities.filter((cell) => ["HIGH", "VERY_HIGH"].includes(cell.priority_band)).length : "Not configured", hasPriority ? "text-priority-700" : "text-slate-500"]];
  if (!hasPriority) return <div className="mx-auto max-w-[1500px]"><div className="mb-6 flex flex-wrap items-end justify-between gap-4"><div><p className="mb-1 text-xs font-bold uppercase tracking-[.15em] text-teal-700">Country workspace</p><h1 className="text-2xl font-bold tracking-tight sm:text-3xl">{jurisdiction?.name} Marine Monitoring Overview</h1><p className="mt-2 text-sm text-app-muted">Operational observation, review, investigation, and field-visit workspace.</p></div><button onClick={() => onNavigate("map")} className="rounded-lg bg-teal-700 px-4 py-2.5 text-sm font-bold text-white">Open monitoring map →</button></div><section className="mb-6 grid grid-cols-2 gap-3 xl:grid-cols-4">{kpis.map(([label, value, color]) => <article key={label} className="rounded-xl border border-app-border bg-white p-4 shadow-sm"><p className="text-xs font-bold uppercase tracking-wide text-app-muted">{label}</p><strong className={`mt-2 block text-2xl ${color}`}>{state.loading ? "…" : value == null ? "—" : typeof value === "number" ? value.toLocaleString() : value}</strong></article>)}</section><div className="grid gap-5 xl:grid-cols-[minmax(0,1.4fr)_minmax(300px,.6fr)]"><section className="rounded-2xl border border-app-border bg-white p-6 shadow-sm"><h2 className="text-xl font-bold">Level-1 operational monitoring</h2><p className="mt-2 text-sm leading-6 text-app-muted">The operational boundary, public submissions, observations, expert review, investigations, and field visits are available for {jurisdiction?.name}.</p><div className="mt-5 rounded-xl border border-slate-200 bg-slate-50 p-4"><strong className="text-sm">Scientific deployment not yet configured</strong><p className="mt-1 text-sm text-app-muted">Habitat suitability and Monitoring Priority are intentionally unavailable for this jurisdiction.</p></div></section><section className="rounded-2xl border border-app-border bg-white p-5 shadow-sm"><h2 className="font-bold">Recent observations</h2><div className="mt-3 divide-y divide-app-border">{state.observations.slice(-4).reverse().map((item) => <div key={item.id} className="py-3"><strong className="block truncate text-sm">{item.species || "Unresolved observation"}</strong><p className="mt-1 text-xs text-app-muted">Observation #{item.id} · {readable(item.verification_status || item.decision)}</p></div>)}{!state.loading && state.observations.length === 0 && <p className="py-4 text-sm text-app-muted">No observations are available. This is a valid empty operational state.</p>}</div></section></div></div>;
  return <div className="mx-auto max-w-[1500px]">
    <div className="mb-6 flex flex-wrap items-end justify-between gap-4"><div><p className="mb-1 text-xs font-bold uppercase tracking-[.15em] text-teal-700">Country workspace</p><h1 className="text-2xl font-bold tracking-tight sm:text-3xl">Jamaica Marine Monitoring Overview</h1><p className="mt-2 text-sm text-app-muted">Current invasive-species monitoring activity and areas requiring attention.</p></div><button onClick={() => onNavigate("map")} className="rounded-lg bg-teal-700 px-4 py-2.5 text-sm font-bold text-white">Open monitoring map →</button></div>
    {state.hasErrors && <div className="mb-4 rounded-xl border border-amber-200 bg-amber-50 p-3 text-sm text-amber-800">Some optional workspace data is unavailable. Available sections remain usable.</div>}
    <section className="mb-6 grid grid-cols-2 gap-3 xl:grid-cols-4">{kpis.map(([label, value, color]) => <article key={label} className="rounded-xl border border-app-border bg-white p-4 shadow-sm"><p className="text-xs font-bold uppercase tracking-wide text-app-muted">{label}</p><strong className={`mt-2 block text-3xl ${color}`}>{state.loading ? "…" : value == null ? "—" : Number(value).toLocaleString()}</strong></article>)}</section>
    <div className="grid gap-5 xl:grid-cols-[minmax(0,1.55fr)_minmax(300px,.65fr)]">
      <section className="relative min-h-[430px] overflow-hidden rounded-2xl border border-app-border bg-[radial-gradient(circle_at_65%_35%,rgba(11,148,137,.2),transparent_28%),linear-gradient(145deg,#dff5ef,#edf5f7)] p-6 shadow-sm"><div className="absolute inset-0 opacity-30" style={{backgroundImage:"linear-gradient(rgba(8,124,117,.16) 1px,transparent 1px),linear-gradient(90deg,rgba(8,124,117,.16) 1px,transparent 1px)",backgroundSize:"38px 38px"}} /><div className="relative max-w-md rounded-xl border border-white/80 bg-white/90 p-5 shadow-lg backdrop-blur"><span className="rounded-full bg-teal-100 px-2.5 py-1 text-[11px] font-bold uppercase tracking-wide text-teal-700">Jamaica workspace</span><h2 className="mt-3 text-xl font-bold">Map-centred monitoring</h2><p className="mt-2 text-sm leading-6 text-app-muted">Explore verified reports, observation hotspots, habitat suitability, and current monitoring priorities in one operational view.</p><button onClick={() => onNavigate("map")} className="mt-4 text-sm font-bold text-teal-700">Explore current layers →</button></div>{topPriority && <article className="absolute bottom-5 left-5 right-5 z-10 max-w-lg rounded-xl border-l-4 border-priority-500 bg-white p-4 shadow-xl"><div className="flex items-center justify-between gap-3"><span className="text-[11px] font-bold uppercase tracking-wider text-priority-700">{readable(topPriority.priority_band)} monitoring priority</span><strong className="text-priority-700">{Number(topPriority.monitoring_priority_score).toFixed(3)}</strong></div><h3 className="mt-2 font-bold">Cell {topPriority.grid_cell_id || `${Number(topPriority.latitude).toFixed(2)}, ${Number(topPriority.longitude).toFixed(2)}`}</h3><p className="mt-1 text-sm text-app-muted">Prioritized using habitat suitability and recent observation evidence.</p></article>}</section>
      <div className="space-y-5"><section className="rounded-2xl border border-app-border bg-white p-5 shadow-sm"><div className="flex items-center justify-between"><h2 className="font-bold">Monitoring snapshot</h2><span className={`rounded-full px-2.5 py-1 text-xs font-bold ${state.freshness?.status === "FRESH" ? "bg-emerald-100 text-emerald-700" : "bg-slate-100 text-slate-600"}`}>{state.freshness?.status === "FRESH" ? "Up to date" : "Freshness unknown"}</span></div><p className="mt-3 text-sm text-app-muted">{state.priorities.length ? `${state.priorities.length} monitoring cells available.` : "No monitoring snapshot is currently available."}</p></section><section className="rounded-2xl border border-app-border bg-white p-5 shadow-sm"><div className="flex items-center justify-between"><h2 className="font-bold">Recent observations</h2><button onClick={() => onNavigate("observations")} className="text-xs font-bold text-teal-700">View all</button></div><div className="mt-3 divide-y divide-app-border">{state.observations.slice(-4).reverse().map((item) => <div key={item.id} className="py-3"><div className="flex justify-between gap-3"><strong className="truncate text-sm">{item.species || "Unresolved observation"}</strong><span className="text-xs text-app-muted">#{item.id}</span></div><p className="mt-1 text-xs text-app-muted">{readable(item.verification_status || item.decision)}</p></div>)}{!state.loading && state.observations.length === 0 && <p className="py-4 text-sm text-app-muted">No observations are available.</p>}</div></section></div>
    </div>
  </div>;
}
